### ISSUE TITLE
Grid or Card view

### ISSUE THREAD

**Issue by skndn60** [darklow/django-suit#103]
In some situations, for example when working with images or model objects that are strongly associated with images, the standard table view of Django admin app is less suitable. A Grid like view, where each model instance is rendered within defined rectangular boundaries, would be more appropriate and make better use of screen real estate. Using the fluid characteristics of Bootstrap such a layout would work quite well.

Would you consider this a feature for Django Suit?

**Comment by kotrakrishna** [comment]
Good work @skndn60  Have you opensourced it? I am looking for exact same customization. Looks like I will have to do it over myself.

**Comment by skndn60** [comment]
I eventually replaced the default admin and Django Suit in favor of a completely custom written backend. Due to code ownership, there are no plans to open source that at this moment.

**Comment by SalahAdDin** [comment]
Awesome man, can you do a pr? please :D

**Comment by gamesbook** [comment]
@skndn60 What happened to all the code that was previously written to be a part of DS... can that at least be shared (i.e. not your custom written backend work)?

**Comment by aababy** [comment]
@skndn60 could you share your grid view code, please?
