### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by skndn60** [darklow/django-suit#108]
I do not know what your "policy" regarding 3rd party parts in DS is, but you might want to consider replacing the Bootstrap icons with the ones offered by Font Awesome:

http://fortawesome.github.io/Font-Awesome/

Advantages:
- more choices
- regularly updated with new stuff
- actual fonts as opposed to images
- various sizes

Font Awesome uses the same syntax as Bootstrap and only requires the addition of a CSS file.

**Comment by willseward** [comment]
:+1:

**Comment by SalahAdDin** [comment]
:+1:

**Comment by mrteera** [comment]
:+1:
