### ISSUE TITLE
Move to Bootstrap 3

### ISSUE THREAD

**Issue by kharazi** [darklow/django-suit#134]
You should move to Bootstrap 3 with care. It is changed.

**Comment by boRk3D** [comment]
+1

**Comment by jbkunst** [comment]
+1

**Comment by darklow** [comment]
Main BS3 discussion is here: https://github.com/darklow/django-suit/issues/262#issuecomment-63809723
You can test and try it out already.
Closing this one.

**Comment by DelightRun** [comment]
Sorry, but i still want to say:

+1

**Comment by iunary** [comment]
+1
