### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by skndn60** [darklow/django-suit#136]
I noticed the current version of jQuery for DS is at release 1.8.3. Is this a constraint of Suit? Reason for asking: I had some weird javascript issues which disappeared when upgrading jQuery to 1.10.2.

**Comment by chrisspen** [comment]
>jQuery that is included in DjangSuit uses it's own namespace Suit.$

This doesn't seem to be the case anymore for Django 1.10. I'm getting errors in jQuery libraries expecting jQuery >2, and the traceback in Chrome is showing it's using the old 1.8 version in Suit.

Why would this be happening?

This is the `<head>` in admin generated for Django 1.10:

    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      
      <link rel="stylesheet" type="text/css" href="/static/suit/bootstrap/css/bootstrap.min.css" media="all"/>
      <link rel="stylesheet" type="text/css" href="/static/suit/css/suit.css" media="all">
      
      <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>
      <script src="/static/suit/js/jquery-1.8.3.min.js"></script>
      <script type="text/javascript">var Suit = { $: $.noConflict() }; if (!$) $ = Suit.$; </script>
      <script src="/static/suit/bootstrap/js/bootstrap.min.js"></script>
      
      <style type="text/css">.required:after { content: '*'; margin: 0 0 0 5px; position: absolute; color: #ccc;}</style>
      
      <script type="text/javascript" src="/admin/jsi18n/"></script>

      <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script type="text/javascript" src="/static/admin/js/inlines.js"></script>
    <script type="text/javascript" src="/static/input_mask/js/jquery.maskedinput.js"></script>
    <script type="text/javascript" src="/static/input_mask/js/text_input_mask.js"></script>

        <meta name="robots" content="NONE,NOARCHIVE"/>
    </head>

**Comment by darklow** [comment]
Fixed in https://github.com/darklow/django-suit/commit/a6e85a05a88d7198404010edeb121f6b89a9d1a9 and released in `v0.2.22`
Now for >= Django 1.9 jQuery 2.2.4 will be used.
If you would like to use any other jQuery version you can now override `suit_jquery` block.
