### ISSUE TITLE
Django Suit rewrite on Bootstrap 3

### ISSUE THREAD

**Issue by darklow** [darklow/django-suit#262]
Few days ago i started Django suit rewrite on Bootstrap 3 and i will keep posting updates in this issue.

Few previous notes about BS3 you can see here: https://github.com/darklow/django-suit/issues/134#issuecomment-39536028

In nearest time i will push ``bs3`` branch to github and you will be able to test it out.
However it will be very early stage and it will be not ready for production for a while.

Currently i am rewriting DS using Django 1.7 rc2 and hopefully i will be able to support both Django 1.6 and 1.7 version.

New features
-----------------

* Two menu variations: Horizontal or vertical
* Two color themes: Dark / Light theme
* Configurable, properly aligned multi-column forms/fieldsets
* and many more

Sneak preview
------------------

Few of new Django Suit design drafts (work in progress)

![suit2-vertical-dark](https://cloud.githubusercontent.com/assets/445304/3751578/5cce7ca0-1800-11e4-80a5-477ec209b84a.png)

Horizontal menu:

![suit2-horizontal-dark](https://cloud.githubusercontent.com/assets/445304/3751581/640a9b52-1800-11e4-8d61-34d2c8ea6659.png)

![suit2-horizontal-light](https://cloud.githubusercontent.com/assets/445304/3751582/640c1bb2-1800-11e4-89dd-c349c4878dff.png)

**Comment by ryan-blunden** [comment]
What is left to do? I can lend a hand potentially.

**Comment by darklow** [comment]
@ryan-blunden thanks.

First of all i haven't received any feedback on how is it.
How is the new look, how are the new lists and so on.

So i am not sure what to do here, i released beta to receive some feedback, to be sure if this is what users will like. I don't want to release new version with BS3 and then everyone will start shouting for tons of problems like bring old UI back and so on.

I am already using new bs3 branch for a couple of projects, but it is not yet ready for production use or clients.

#### About what is left to do:

1. Deal with responsive forms - this is one of most complicated things what needs to be finished. It is very hard to make a layout with multiple fields in a row and with good responsive wrapping. I doubt anyone could help on that, i tried lot of different approaches, but i am not sure which is best one. This needs to be discussed in separate issue i guess.
2. Vertical / left side menu (as it was in) However i like new horizontal much better, not sure if vertical is still needed (some feedback would be good).
3. Lot's of small things - adjust to bs3 syntax lot of templates like change password forms, user admin, error messages, change form link bar and so on. 
4. Finish header, allow putting shortcut icons there.
5. Restore support for 3rd party apps (except django-cms) by applying new bs3 markup.

**Comment by meetbryce** [comment]
I personally much prefer the sidebar than horizontal sorry.

For forms, I wouldn't see a problem with having each filed on a separate
line.

On Tuesday, 3 February 2015, Kaspars Sprogis <notifications@github.com>
wrote:

> @ryan-blunden <https://github.com/ryan-blunden> thanks.
>
> First of all i haven't received any feedback on how is it.
> How is the new look, how are the new lists and so on.
>
> So i am not sure what to do here, i released beta to receive some
> feedback, to be sure if this is what users will like. I don't want to
> release new version with BS3 and then everyone will start shouting for tons
> of problems like bring old UI back and so on.
>
> I am already using new bs3 branch for a couple of projects, but it is not
> yet ready for production use or clients.
> About what is left to do:
>
>    1. Deal with responsive forms - this is one of most complicated things
>    what needs to be finished. It is very hard to make a layout with multiple
>    fields in a row and with good responsive wrapping. I doubt anyone could
>    help on that, i tried lot of different approaches, but i am not sure which
>    is best one. This needs to be discussed in separate issue i guess.
>    2. Vertical / left side menu (as it was in) However i like new
>    horizontal much better, not sure if vertical is still needed (some feedback
>    would be good).
>    3. Lot's of small things - adjust to bs3 syntax lot of templates like
>    change password forms, user admin, error messages, change form link bar and
>    so on.
>    4. Finish header, allow putting shortcut icons there.
>    5. Restore support for 3rd party apps (except django-cms) by applying
>    new bs3 markup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/darklow/django-suit/issues/262#issuecomment-72610697>.
>


-- 
Cheers,
Bryce York (*+61 466 466 124*)

<http://www.linkedin.com/in/meetbryce>
<http://www.facebook.com/meetbryceyork>  <http://www.twitter.com/meetbryce>

Shopify makes it easy to open an online store by providing all the tools
and help you need. Click here to try it for free!
<http://www.shopify.com/?ref=done-digital>

Does your Wordpress blog need a facelift? Check out our Medium.com inspired
Wordpress theme at WPMedium.com
<http://www.wpmedium.com/?utm_source=email&utm_medium=signature&utm_campaign=meetbryce>

**Comment by gamesbook** [comment]
I support the sidebar for one main reason - modern screens have far more
horizontal space available to them than vertical space and the fewer
horizontal "divs" (sections of screen dedicated to an information type),
the more space for showing actual data.  Also; continuity - users do not
like major changes to the interface without a very good reason.  So an
option for a horizontal menu is good & may be useful in some cases, but the
existing vertical menu MUST continue to work.

**Comment by darklow** [comment]
@meetbryce @gamesbook thank you for feedback, next thing i'll do is port left side menu to bs3 version.

**Comment by ryan-blunden** [comment]
Re what's left to do:

1) Yep, really hard to do and I don't think this is required for version 1 of BS 3. The majority of the admin should be responsive but not everything is going to be able to be done easily on a mobile.

A custom solution does need to be worked out for the horizontal nav for the admin and individual apps and enabling horizontal scrolling for these nav items would work well if the content overflows the container.

2) I definitely want to see this back as well.

3) Can you create individual issues for this so I know what I can help with exactly.

4) I think this can wait post 1.0 as well.

5) This is your call but ideally, the maintainer of these apps would help. What's the support like for other apps?

**Comment by cho-is** [comment]
You've done a really good job @darklow developing this new fresh theme! I was looking for some horizontal menu approach and I ended up here. Looking perfect in mi 13'' laptop!

**Comment by darklow** [comment]
Updates:
* Rewrote principles how BS3 markup is applied to widgets
* Horizontal search filter bug fix
* Auth app user/group admin style added for roles, etc.

**Comment by Edke** [comment]
@darklow Would like to thank you for taking this road. Definately creating new admin template based on bootstrap is best django-suit can do in this moment. Will support this, will buy OEM if that can help to reach bootstrap stable version.

**Comment by darklow** [comment]
I just uploaded `bs3` branch as `0.3a1` version to pypi server.
Now you can install bs3 branch from pypi using `pip` or `easy_install` just like stable releases.
Which also makes it easier to be referenced in `requirements.txt` and follow alpha updates.
PS. If your `pip` shows that this version doesn't exist, update you pip version.

```
pip install django-suit==0.3a1
```

**Comment by Edke** [comment]
@darklow Man that looks awesome. Looks like this is already in stage suitable for production. Are there some issues still pending that should block this release from using in production ?

**Comment by darklow** [comment]
@Edke There are some issues regarding to CSS. Like error messages, etc.
Also there is almost no support for 3rd party apps.
I am still deciding what to do with them.
Probably i will create separate app for each 3rd party app instead of adding everything to core.
For example: `django-suit-filer`, `django-suit-select2`, etc.

**Comment by Edke** [comment]
> I am still deciding what to do with them.
> Probably i will create separate app for each 3rd party app instead of adding everything to core.
> For example: django-suit-filer, django-suit-select2, etc.

This is IMHO good approach because this way I'm aware what django-suit supports and what not and have control over those sub packages.

**Comment by fmartingr** [comment]
:+1: I proposed that approach a while ago, and I use that on the two suit third-party admin rewrites.

**Comment by meetbryce** [comment]
Just my 2c but I think that's a great approach as well. Being able to use
the core and only have to worry about support for additional apps if
they're actually an issue for me.

**Comment by SalahAdDin** [comment]
@darklow, why put you a top menu bar? I think that side menu bar is much better.
And, why put you the many to many fields as vertical filter? I think that is better horizontal, tbetter use of the space, you wasted much space on the dashboard, also lack the time and date, well, these useful things in the previous version.
The tabs don't work correctly, i think that can put the breadcrumb and the model's links in the same div, breadcrumb in left side, and model's links in right side. Why change you your filters fields for the django admin's deafault filters? They are very anoying, i like your filters fields :D. don't have support yet django-import-export ?
In general space is wasted, but it looks very nice, there are many things I liked, for example, the style, the colors, the band models app.
You can see in this pics:
![firtpsbs3](https://cloud.githubusercontent.com/assets/5034215/7330547/226d3c66-eab6-11e4-8a9a-f434178eff19.png)
![fourthpsbs3](https://cloud.githubusercontent.com/assets/5034215/7330548/226e53b2-eab6-11e4-954e-c909867d2c1a.png)
![secondpsbs3](https://cloud.githubusercontent.com/assets/5034215/7330550/227061fc-eab6-11e4-8dda-f962a4e7e284.png)
![thirdpsbs3](https://cloud.githubusercontent.com/assets/5034215/7330549/227004a0-eab6-11e4-8fd8-52886746c2f7.png)

It's all now, if you want my help, i will like help you :D

**Comment by gamesbook** [comment]
I am sure there was a earlier thread where many (most?) users voted for a
side-menu (the current behaviour) and it was agreed that this would happen?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by darklow** [comment]
@SalahAdDin You should use 0.2.x versions for production use. 
That is why this `0.3a1` is `alpha1` version, a lot of things are not complete yet.

1. Only top menu currently is finished, i haven't started work on side menu yet
2. You can use centered filters like in v1 using `suit_list_filters_position = 'center'` (this will be default version again soon)

**Comment by SalahAdDin** [comment]
I want help you, what can i help you?

**Comment by SalahAdDin** [comment]
Man, i think that you should merge django-suit-local whit django-suit for localization. :+1: 
otherwise to put trans template tag in the templates?

**Comment by kcolton** [comment]
:+1:

**Comment by ibooj** [comment]
SalahAdDin commented on 25 Apr
"don't works for me. I put col-lg-8 instead of col-lg-4."

form_size = SUIT_FORM_SIZE_HALF

**Comment by meetbryce** [comment]
HI @darklow, 

Is this feature still in progress? Have been using this on a project and really enjoying it, would love to see it migrate to production ready or alpha though.

Thanks for your great work so far. Can't imagine ever using the default admin again!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by saritasa** [comment]
Hi @darklow,

Do you want to move this project to kickstarter and devote your full time on it? 

The same way as with Django Rest Framework: https://www.kickstarter.com/projects/tomchristie/django-rest-framework-3

I think Django Community would benefit a LOT from having very nice and modern UI admin. Even new django flat admin is not that 'attractive'.

**Comment by Nekmo** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by ryan-blunden** [comment]
I would happily contribute funds to this project.

**Comment by krasnoperov** [comment]
![shut-up-and-take-my-money](https://cloud.githubusercontent.com/assets/4581825/9350615/bb05a72c-466b-11e5-944e-4b2e5ee8d395.jpg)

**Comment by yigitguler** [comment]
+1

**Comment by vladyslav2** [comment]
Nice idea

**Comment by darklow** [comment]
Thank you all. Such ideas and posts gives me extra motivation.

Unfortunately it is not the money problem, as it is more "not enough free time" problem.
Not always money can buy time you need.

Also what makes maintaining hard are constantly updating Django admin templates and conflicts that arises supporting so big range of versions. The more extra features i add, the more hard maintaining becomes for future versions. So i am still thinking of best solution for stable and good future and version release scheme for Django Suit and bs3 branch will be finished soon, not so much left anyways :)

**Comment by Nekmo** [comment]
We are a small company and we are using your theme for our future
projects. We really like your theme. :-) However, we have a problem.

We are making improvements in the admin. We are creating our own views.
Right now, we have to use Bootstrap 2. We want to use Bootstrap 3.

We understand that you have no time. Therefore, we would like to change
your current theme and integrate him Bootstrap 3. If you wish, when we
finish, we can deliver the result. We are only going to make a patch. But
we believe that will be useful to others.


Un cordial saludo:
-- Nekmo.

Sitio web: http://nekmo.com
Dirección de contacto: contacto@nekmo.com
XMPP/Jabber: contacto@nekmo.com
Google+: Nekmo Com

2015-08-19 12:45 GMT+02:00 Kaspars Sprogis <notifications@github.com>:

**Comment by darklow** [comment]
@Nekmo Are you using bs3 branch or checked it at least for Bootstrap3?

**Comment by Nekmo** [comment]
We tested the dev bs3 branch ago. We understood that it was not over.

We have tried to change Bootstrap 2 to Bootstrap 3. Some things don't look good. But we think it's easy to fix.

**Comment by nypisces** [comment]
bs4 is coming...

**Comment by SalahAdDin** [comment]
@nypisces yeah, and foundation 6 too...

What's up @darklow ?

**Comment by luison** [comment]
Hi @darklow- I am a colleague of @Nekmo and have been working for a few days over a fork of your develop branch in order to try to do a quick adapt to support BS3. Rather than a redesign this is our try to make it "compatible with".
So far we've fixed most issues and we are stuck in some minor detail, specially on some inputs that don't render as bs3 and making all of them more or less consistent.
After having a look at your code and with some of the issues we can not fix I am going to take the route of completely parsing bootstrap stylesheet from less sources so I can use its  standart variables  (I beleive you do that in bs3) and then just make suit.css contain those overrides. 
I am also going to try to extend the failing classes and maybe the base layout elements from bs3 classes.
Our main concern is that your BS3 branch is obviously more a rewrite of the whole theme and I am unclear if our work would be more productive there than on "patching" the previous version. Do you have a detailed list of the remaining work to be done on the BS3 branch? Is that public? Thanks.

**Comment by darklow** [comment]
@luison At the very beginning i tried rewrite bs2 to bs3, but it was too complicated. Also many Django templates were updated at latest Django versions and then i realised i need clean rewrite and started bs3 branch: https://github.com/darklow/django-suit/tree/bs3
As i said before i am already using bs3 alpha version for many projects already.

What are missing: 3rd party app support, alert boxes and warnings, better responsive support some more advanced components.

Why not try installing and see for yourself?
```
pip install django-suit==0.3a1
```

In next week i have scheduled time to work on bs3 branch and go through the most important issues.

**Comment by luison** [comment]
Thanks for prompt reply.  We'll try to incorporate to a project of our own and check. As I said we are willing to spend some time on it as we really need to have BS3 support. It would be great being able to help/complement your work rather than redo part of it, so a detailed list of missing features and proposed solutions would be great.

**Comment by teone** [comment]
Hi @darklow, thanks for your awesome work!

I tried it today and it seems to work pretty well. I just have a question:
in the "old" suit configuration where possible to specify `MENU` and `MENU_EXCLUDE` arrays to add or remove elements. Is that option still available? How could I add it to `apps.py`?

**Comment by SalahAdDin** [comment]
@darklow what's up man with this?

**Comment by yuchant** [comment]
Will happily contribute funds as well. Keep up the good work.

**Comment by darklow** [comment]
@yuchant @SalahAdDin @ryan-blunden @krasnoperov 
You should read this first ;)
https://github.com/darklow/django-suit/issues/475
Closing this issue in regarding of #475 
Bs3 is dropped, Long live bs4! :)

**Comment by yuchant** [comment]
@darklow  You're a boss and you know it

**Comment by darklow** [comment]
@Edke @ryan-blunden @krasnoperov 
Regarding to new upcoming v2 #475. Some users with existing licenses asked if they can contribute or buy an upgrade fee for v2 in advance. So even if this is complete rewrite, all you current licenses will be valid for v2 and therefore will be no upgrade fee. If you want to show your appreciation and support development of v2, you can use Donate feature or buy an extra license here:
http://djangosuit.com/pricing/#v2
Thank you!

**Comment by Edke** [comment]
@darklow will contact you by email about licencing possibilities
