### ISSUE TITLE
There seems to be a problem with embedding the CKEditor into SortableStackedInline

### ISSUE THREAD

**Issue by mkotsalainen** [darklow/django-suit#268]
See image:
![image](https://cloud.githubusercontent.com/assets/180238/3995861/8152bd0a-292d-11e4-9657-6d8339444535.png)

I'm trying to figure out what is wrong. Looks like a css issue? Same issue with normal StackedInlines.

Using django-suit==0.2.9 and django-suit-ckeditor==0.0.2

**Comment by davidlesieur** [comment]
This issue was there first, but should probably be marked as a duplicate of #334, which has more info.

**Comment by cubiczx** [comment]
In my case I do not care.
When i use a SortableStackedInline or SortableTabularInline the form field with CKeditor enabled not show correctly.

**Comment by SalahAdDin** [comment]
Did you try using django-ckeditor?

**Comment by cubiczx** [comment]
I test with django-suit-ckeditor, django-suit-redactor and django-tinymce explain in documentation http://django-suit.readthedocs.org/en/latest/wysiwyg.html

**Comment by cubiczx** [comment]
I test with django-ckeditor and i have a problem when use a ckeditor in a Tabular inline and change order of elements the iframe is empty.

**Comment by SalahAdDin** [comment]
You cand report this issue in django-ckeditor, and here, @darklow maybe can help you.

**Comment by cubiczx** [comment]
Thanks

**Comment by cl4rke** [comment]
+1

**Comment by darklow** [comment]
Fix included in newest v0.2.24
