### ISSUE TITLE
django suite overwrites my 404 and 500 templates

### ISSUE THREAD

**Issue by tomdagz** [darklow/django-suit#297]
I'm using django 1.6.5 and I installed django suite 0.2.11, when I get an error always django suite shows its 404 template. I have my own errors templates.

**Comment by pythdasch** [comment]
I'm reopening this issue, because this error is still coming and would be great to not have to put our app before suits which has to be before django.contrib.admin. 

I don't think django-suit need to have 404 or 500 template

I spent like hours to know why it was happening

**Comment by darklow** [comment]
By the way, your app(s) should always be before `suit` and `admin` in `INSTALLED_APPS` as that is the only and only proper way to extend either suit or admin, so your frustration about putting your app first is quite strange.

**Comment by pythdasch** [comment]
maybe you're right, thx for the reply :)
