### ISSUE TITLE
LinkedSelect for raw fields

### ISSUE THREAD

**Issue by Pawamoy** [darklow/django-suit#319]
Hi darklow,
Could it be possible to add LinkedSelect support for raw fields ?
I tried to add it in my inlines but it doesn't work when the fields are raw ;(

Regards,
Pawamoy

**Comment by Pawamoy** [comment]
More than 2 years without update, closing

**Comment by gamesbook** [comment]
https://github.com/digi604/django-smart-selects

seems to work well enough with django-suit
