### ISSUE TITLE
Inconsistent action dropdown location

### ISSUE THREAD

**Issue by chrisspen** [darklow/django-suit#321]
I'm noticing that the position of the action dropdown on changelist pages sometimes changes unexpectedly.

e.g. I have SUIT_CONFIG MENU list like:

    [{
        'label': 'MyModel',
        'models': (
            'myapp.mymodel',
        )
    }]

Note, Suit generates a top level section link that is the same as the link for the first model listed in that menu section. So in this case I have a menu section that looks like:

    MyModel
        MyModel

And they both have identical links. However, if I click the first link, *sometimes* it will show 100 items and the action dropdown will show up at the top of the page. If I refresh the screen or click the second link, only 20 items will be listed and the dropdown will show at the bottom of the page. This behavior seems non-deterministic, as I'm not always able to reproduce it.

Is this a bug, or is there some feature here I'm misunderstanding or mis-using?

**Comment by jerzyk** [comment]
this happens a lot, it looks like something is changing classes already loaded in memory. after POST or several refreshes - situation stabilizes. Similar things happens to date formats (changing between first GET and POST).

**Comment by gamesbook** [comment]
I don't have date format issues, but the location of the action list drop-down does move around.

**Comment by chrisspen** [comment]
I "fixed" this by specifying these values in all my ModelAdmins:

    actions_on_top = True
    actions_on_bottom = False

Otherwise, it seems to pick at random. I'm not sure that this is strictly a django-suit related issue.
