### ISSUE TITLE
Duplicate model entry

### ISSUE THREAD

**Issue by jonas-eberle** [darklow/django-suit#339]
Hi, 

is there a possibility to duplicate a model entry in the admin interface? That would be very helpfull for admin users who have to add entries of a model with similar content. 

Thanks, 
Jonas

**Comment by darklow** [comment]
I don't think this question is related to Django Suit, but Django itself.
There are proxy models for that: https://docs.djangoproject.com/en/1.7/topics/db/models/#proxy-models

**Comment by jonas-eberle** [comment]
I don't want to duplicate or proxy a model. The admin user should have the possibility to copy the content of an entry to create a new entry in the same model (copying & pasting most of the fields is not really a nice workflow for that).

**Comment by darklow** [comment]
Have you tried `save_as`?
http://stackoverflow.com/questions/180809/in-the-django-admin-interface-is-there-a-way-to-duplicate-an-item

**Comment by jonas-eberle** [comment]
Wow, thank you very much. That was easy. I didn't found this hint before.
