### ISSUE TITLE
Admin list editable fields width

### ISSUE THREAD

**Issue by Arti3DPlayer** [darklow/django-suit#345]
Is there any way to set width of inputs in change_list ?

http://awesomescreenshot.com/0644juqace

**Comment by darklow** [comment]
1. Use one of these two solutions to extend form class and add another that is used in editable lists:
http://stackoverflow.com/questions/7065982/list-editable-and-widgets
More about extending form widgets: http://django-suit.readthedocs.org/en/develop/widgets.html#widgets

2. Or just override width by CSS
