### ISSUE TITLE
Ajax Save feature?

### ISSUE THREAD

**Issue by MikeSmith12222** [darklow/django-suit#347]
Hi guys,

this is a feature request:
I love how the "save" buttons stick via affix when editing something in the backend, 
BUT I hate when the screen moves back to the top after a save.

My suggestion is to implement the "save"-buttonbox as ajax, so that I am staying where I am on the screen and do not need to scroll down again after saving.

**Comment by darklow** [comment]
Django Suit is just a skin for original Django admin and ajax save will break a lot of things in lot of apps.
If Django will ever decide to go for ajax save (which i doubt) then we can reopen this issue.
