### ISSUE TITLE
Missing repo tags

### ISSUE THREAD

**Issue by dw** [darklow/django-suit#349]
v.0.2.12 is the currently pip-installable version, but there is no tag for it in your Git repository.

**Comment by darklow** [comment]
Thanks for letting me know, i'll fix that.
Just to know better, how do you use tags?

**Comment by darklow** [comment]
Apparently i just forgot to push the tags.
Now it is fixed.

**Comment by dw** [comment]
Hi darklow! I was diffing various bits of the repo to figure out what had changed since your new branch :)
