### ISSUE TITLE
Searchable select list

### ISSUE THREAD

**Issue by JBPressac** [darklow/django-suit#353]
Hello,
Thank you for your project. Would it be possible to implement searchable select lists as on this example http://www.grocerycrud.com/examples/employees_example. Or as found on the data-live-search="true" example on http://silviomoreto.github.io/bootstrap-select/.
Thanks,

**Comment by JBPressac** [comment]
Hello,
I tried to use `raw_id_fields` which has a search functionality and which works fine. 

I also realised that the keyword for my whished functionality was not 'searchable' but 'autocomplete'.  Autocomplete fields are implemented for instance in https://github.com/yourlabs/django-autocomplete-light.
Thanks,

**Comment by darklow** [comment]
Have you checked select2 integration example?
http://djangosuit.com/admin/examples/city/7/

**Comment by JBPressac** [comment]
Wonderfull ! I suppose this feature is comming from https://github.com/applegrew/django-select2 ?

**Comment by JBPressac** [comment]
Wonderfull ! I suppose this feature is comming from https://github.com/applegrew/django-select2 ?

**Comment by JBPressac** [comment]
Wonderfull ! Just for documentation, I just specify here that the select2 feature is comming from the library https://github.com/applegrew/django-select2.
