### ISSUE TITLE
Django 1.8 - Removed in Django 1.9 warning

### ISSUE THREAD

**Issue by Koed00** [darklow/django-suit#354]
django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9.
Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
suit/admin.py:5:  `from django.contrib.contenttypes import generic`

**Comment by gleb-chipiga** [comment]
+1

**Comment by xrage** [comment]
+1

**Comment by azappa** [comment]
+1

**Comment by SalahAdDin** [comment]
+1 :+1:

**Comment by kirnap** [comment]
+1

**Comment by leonx075** [comment]
+1
