### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by Pawamoy** [darklow/django-suit#355]
Does anyone have an idea on how to (re)add a button in suit interface for changing the current language?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by Pawamoy** [comment]
In my own project, I currently use this code to change the language:

```html
<div class="btn-group">
    <button class="dropdown-toggle btn" data-toggle="dropdown">
        {% trans "Language" %} <span class="caret"></span>
    </button>

    <ul class="dropdown-menu">
        {% for lang in LANGUAGES %}
            <li>
                <form action="/i18n/setlang/" method="post">{% csrf_token %}
                    <input type="hidden" name="language" value="{{ lang.0 }}"/>
                    <input class="lang-submit" type="submit" value="{{ lang.1 }}" />
                </form>
            </li>
        {% endfor %}
    </ul>
</div>
```

So I tried to add about the same thing in the header of Suit's HTML base, but hitting the submit button does nothing, besides the dropdown is displayed BEHIND the body, and I can't manage to display it over the body.

It could be a start if someone else want to try :construction_worker:

**Comment by TimurAykutYildirim** [comment]
Any updates on this issue? I'm using v0.2.18 and I want to make admin interface all in Turkish. I can help with translation if needed?

**Comment by carlosribas** [comment]
I installed django-suit to test and I also want to know how to enable a language switcher. Does anyone did it?

**Comment by SalahAdDin** [comment]
It's easy:
override the django admin template, base_site, and add this in the block `header_contet`or whatever you want:
```python

    <div class="header-content">
    <form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}" />
    <select name="{% trans 'language' %}" style="width: auto;">
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    {% for language in languages %}
    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
        {{ language.name_local }} ({{ language.code }})
    </option>
    {% endfor %}
    </select>
    <input class="btn btn-high" type="submit" value="{% trans 'Go' %}" style="vertical-align: top;"/>
    </form>
    </div>
```

**Comment by carlosribas** [comment]
Great! It worked, thanks.

**Comment by Pawamoy** [comment]
Thank you @SalahAdDin, just a comment about your snippet: you should not translate `language` in `<select name="{% trans 'language' %}" style="width: auto;">`. The view is waiting a POST field named `language` (not a traduction of it). Also remember to add `{% load i18n %}` at the top!
