### ISSUE TITLE
HiddenInput widget is not hidden

### ISSUE THREAD

**Issue by raratiru** [darklow/django-suit#367]
forms.HiddenInput() when defined as widget in forms.py, will not produce the expected result in admin pages.

Django==1.8.1
django-suit==0.2.13
python==3.4.1

models.py

```
class Site(models.Model):
    postal_code_key = models.ForeignKey(
        PostalCode,
        )
    geo_point = geomodels.PointField(
        unique=True,
        srid=4326
        )
    location_key = models.ForeignKey(
        Location,
        )
```

forms.py

```
class AddSiteForm(forms.ModelForm):
    point = GeopositionField()
    form_postal_code = forms.CharField()
    location_key = autocomplete_light.ModelChoiceField('LocationAutocomplete')

    class Meta:
        model = Site
        fields = ['geo_point', 'postal_code_key', 'location_key']
        widgets = {'geo_point': forms.HiddenInput(), 'postal_code_key': forms.HiddenInput()}
        ...
```

Although django admin renders the widget correctly:

![screenshot from 2015-05-09 22 36 55](https://cloud.githubusercontent.com/assets/6132160/7551711/57ba935e-f69c-11e4-9774-770a4934c9e7.png)

Django-suit, will not:
![screenshot from 2015-05-09 22 38 24](https://cloud.githubusercontent.com/assets/6132160/7551713/632d40ec-f69c-11e4-8656-72b6ebb68443.png)

**Comment by Gustavosdo** [comment]
+1
