### ISSUE TITLE
SortableStackedInline and SortableTabularInline not show CKeditor correctly

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#374]
When i use a SortableStackedInline or SortableTabularInline the form field with CKeditor enabled not show correctly.

**Comment by darklow** [comment]
Please specify Django and Django Suit versions and code example

**Comment by cubiczx** [comment]
Django==1.6.2
django-suit==0.2.13

Solved with inline form

```python
class TratamientoFormInline(ModelForm):
    class Meta:
        model = Tratamiento
        fields = "__all__" 
        widgets = {
            'tratamiento': CKEditorWidget(editor_options=_ck_editor_config),
        }
```

**Comment by SalahAdDin** [comment]
Are there any other solution?

**Comment by cubiczx** [comment]
No

**Comment by SalahAdDin** [comment]
What it's your ckeditor config?

**Comment by cubiczx** [comment]
django-ckeditor==4.4.8
django-suit-ckeditor==0.0.2

**Comment by SalahAdDin** [comment]
are you using ckeditor? i don´t need use it.

**Comment by cubiczx** [comment]
Solved with inline form.
Issue is closed
