### ISSUE TITLE
When order SortableStackedInline CKEditor content destroy

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#375]
When click to order SortableStackedInline, field with CKEditor (django-suit-ckeditor) or tinyMCE (django-tinymce ) content destroy Iframe empty.
When use Redactorjs (django-suit-redactor) run it works perfectly, What is the difference?

**Comment by SalahAdDin** [comment]
But, you don't need use django-suit-ckeditor, django-ckeditor is enough.

**Comment by cubiczx** [comment]
Ok, monday test and reply the solution.

**Comment by cubiczx** [comment]
Solved change iframe for div
Django==1.6.2
django-suit==0.2.13
django-ckeditor==4.4.8
django-suit-ckeditor==0.0.2

**Comment by SalahAdDin** [comment]
Where did you change the iframe for div?

**Comment by cubiczx** [comment]
I use the plugin divarea for suit-ckeditor

**Comment by SalahAdDin** [comment]
Which is these?
