### ISSUE TITLE
When use Change list sortable can not sort by other fields

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#377]
When use Change list sortable can not sort by other fields.
Ex:
ordering = ['orden', 'title'] --> Not work
sortable = 'orden'

**Comment by darklow** [comment]
Please provide code of admin class and particular model class and specify Django Suit and Django versions

**Comment by cubiczx** [comment]
Django version 1.6.2
django-suit==0.2.13

models.py:
```python
class Anexo(models.Model):
    # Anexo Fields
    title = models.CharField(_(u'Título'), max_length=255)
    fichero = models.FileField(upload_to="anexos")
    orden = models.PositiveSmallIntegerField(default=0, blank=False, null=False)

    def __unicode__(self):
```

admin.py:
```python
class AnexoAdmin(SortableModelAdmin):
    form = AnexoForm
    fieldsets = [
        (u'Título', {
            'classes': ('full-width',),
            'fields': ['title']}),
        ('Fichero', {
            'classes': ('full-width',),
            'fields': ['fichero']})
    ]
    list_display = ('title', 'fichero', 'orden')
    list_filter = ['orden']
    search_fields = ['title']

    ordering = ['orden', 'title']
    sortable = 'orden'
    pass
```

**Comment by darklow** [comment]
Ok, sorry misunderstood, yes this is kind of disadvantage you have to deal with, when using list sortable.  If you use manual sorting - SortableModelAdmin, you cannot sort by other columns other than order column.

**Comment by cubiczx** [comment]
I figured it was not implemented this combined functionality.

**Comment by darklow** [comment]
And this is very rarely needed, what is the point of second order field, if you control each item order manually?
And in case if sorting by another fields, theoretically we could hide the arrow, but then it can get confusing, etc.

**Comment by cubiczx** [comment]
The problem is that you can remove the order by order field.
And as the title field is active for ordering you will usually work.
If there must be also in the fields ManyToManyField column has no link to order.
In this case also should turn off.
