### ISSUE TITLE
Add welcome-msg block to base.html for extending

### ISSUE THREAD

**Issue by edgecaselabs** [darklow/django-suit#379]
Django has a {% block welcome-msg %} wrapper around the welcome message:
https://github.com/django/django/blob/1.7c3/django/contrib/admin/templates/admin/base.html#L29

Would be nice to have that in the Suit base.html for those of us who use custom User models.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
@darklow thanks man.

**Comment by edgecaselabs** [comment]
:+1:
