### ISSUE TITLE
0.3a1 not respecting SUIT_CONFIG (Django 1.8)

### ISSUE THREAD

**Issue by birdsarah** [darklow/django-suit#382]
Hi,

I initially tried 0.3a1, which looks great! But it wasn't respecting my SUIT_CONFIG.

I downgraded to 0.2.13 and it did respect it.

Any thoughts? Any additional information I can provide to help?

Sincerely,

Sarah Bird

**Comment by darklow** [comment]
You must use new Django >= 1.7 style config to configure 0.3a1:

Read more here:
https://github.com/darklow/django-suit/issues/262#issuecomment-63809723

**Comment by birdsarah** [comment]
This worked great - thank you!
