### ISSUE TITLE
Re-use of form layout logic

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#386]
There are sections of my site that are not part of the admin.  I would like to maintain a consistent look-and-feel in all places.  Are there guidelines or docs anywhere on how to set up templates such that forms are rendered in the same way as DjangoSuit?

**Comment by darklow** [comment]
Can you be more specific?
Do you mean in terms of CSS or in terms of python?

**Comment by gamesbook** [comment]
In terms of the CSS and the template code that lays out the form sections, headers, groups etc. (I assume both are needed to give the correct appearance.)

**Comment by darklow** [comment]
Django Suit just applies some extra HTML and CSS to original Django admin forms output and templates, so you will need quite a lot admin side dependencies to achieve that.
It can be possible, but i think it won't be easy. Since i have never done that i won't be able to help you.

**Comment by gamesbook** [comment]
Would you be able to indicate where/how in your code you apply the extra HTML
and CSS?

**Comment by darklow** [comment]
http://django-suit.readthedocs.org/en/develop/#templates
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#admin-overriding-templates

**Comment by gamesbook** [comment]
Thanks. I am already inheriting from the base_site.html template but I assumed there would be others related more to form layout - obviously this is not the case.
