### ISSUE TITLE
SUIT_CONFIG Menu Label permissions user with group

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#387]
When a user does not have the permissions assigned directly and has through a group setting SUIT_CONFIG - MENU - permissions not working.

**Comment by SalahAdDin** [comment]
Can you put an example?

**Comment by cubiczx** [comment]
I have a user without explicit permissions, and these have a group X and this group X have specific permissions. The group have permissions to add abreviatura. And when open admin with this user menu not are showed.

```Django
# Django Suit configuration example
SUIT_CONFIG = {
    'MENU': (
        'sites',
        {'label': u'Exportación', 'icon':'icon-share', 'url': '/admin/exportacion/', 'permissions': 'auth.add_abreviatura'},
    )
}
```

**Comment by darklow** [comment]
Please specify Django and Django Suit versions and code example

**Comment by cubiczx** [comment]
Django==1.6.2
django-suit==0.2.13

**Comment by cubiczx** [comment]
any ideas?

**Comment by cometsong** [comment]
@cubiczx 
I was having this same problem with permissions, starting with permission name `auth. ...`
Try changing that name to `your_app_name.add_abreviatura` instead.
That made a similar setup work on my end.  Both for a group *with* that permission and a group *without*.

**Comment by darklow** [comment]
@cubiczx @cometsong is right, you need to use app prefix as described here:
https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.has_perms
You can easily test right string to use using `./manage.py dbshell` and selecting user and verifying if `user.has_perms(['my_app.my_perm'])` returns True.
