### ISSUE TITLE
django-select2 search fields fails to initialize after page reload

### ISSUE THREAD

**Issue by Xaroth** [darklow/django-suit#388]
I'm having a bit of a strange issue.

When I'm showing an admin page with 2 TabularInline inlines, both having a (different) foreignkey that is being shown using django-select2 (as per the exmaple). the first page load it works 100% fine, however, after visiting the page again, it doesn't seem as if select2 initializes properly.

![image](https://cloud.githubusercontent.com/assets/180744/8244564/931878ee-1622-11e5-903a-6cbb9b736a96.png)

This is after runserver/uwsgi starts up, reloading the page makes it show like this:

![image](https://cloud.githubusercontent.com/assets/180744/8244570/a7f2d8d6-1622-11e5-99fb-6aed8b53e9b2.png)

Added note: This seems to affect multiple browsers, also, I do not see any js errors in the developer console.

**Comment by 9dogs** [comment]
Got the same issue. Apparently select2.min.css loading code doesn't always include in the page for some reason. As a dirty workaround you can explicitly include
```python
class Media:
        css = {
            'all': ('django_select2/css/select2.min.css',)
        }
```
in your class form.

**Comment by Xaroth** [comment]
Yep, that seems to fix it.. an odd issue that.
