### ISSUE TITLE
LinkedSelect fails relationship with ManyToManyField

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#390]
When use LinkedSelect in field type ManyToManyField always show relationship 1.

**Comment by darklow** [comment]
Please specify Django and Django Suit versions and code example

**Comment by cubiczx** [comment]
I solve with relationship through table

**Comment by SalahAdDin** [comment]
I don't understand your problem.

**Comment by cubiczx** [comment]
This issue can be deleted

**Comment by SalahAdDin** [comment]
Was a problem from your models?
