### ISSUE TITLE
incorrect timestamp on the top of the template

### ISSUE THREAD

**Issue by kouroshparsa** [darklow/django-suit#399]
The timestamp that is displayed on the top of the template is 42 minutes ahead of the local time.

![z](https://cloud.githubusercontent.com/assets/5926527/8613480/7c7c4552-2694-11e5-9002-47232ee57d67.png)

```
<div class="header-column">
   <span class="date"> Friday, 10th July 2015</span><br>
   <span class="time" id="clock">01:25</span>
</div>
```

**Comment by darklow** [comment]
It shows your server time.
If you're using Unix, type `date` in console and compare
