### ISSUE TITLE
Errors do not display on login form (because of this_is_the_login_form hack)

### ISSUE THREAD

**Issue by bencharb** [darklow/django-suit#400]
Error messages are not displaying on the login form. It looks like django removed this_is_the_login_form. The suit template still references this_is_the_login_form, which prevents errors from displaying
Related ticket: https://code.djangoproject.com/ticket/21911

**Comment by SalahAdDin** [comment]
:+1:  @darklow

**Comment by willseward** [comment]
+1

**Comment by marco-santamaria** [comment]
+1

**Comment by bashu** [comment]
+1 django 1.7.9

**Comment by gonzalobustos** [comment]
+1

**Comment by brunocascio** [comment]
+1

**Comment by darklow** [comment]
Should be fixed by this PR:
https://github.com/darklow/django-suit/pull/410

**Comment by darklow** [comment]
Will be included in newest version. Releasing it today.
