### ISSUE TITLE
Option.module_name isn't valid in Django 1.8

### ISSUE THREAD

**Issue by reggieriser** [darklow/django-suit#405]
In Django 1.8, Option.module_name as been renamed to model_name.  You'll see a deprecation under 1.7, but some silent failures leading to missing parts of form names in rendered templates in Django 1.8.  See usages in change_form.html (may be others too).

Here's the deprecation when running under Django 1.7.x:

[...]/lib/python2.7/site-packages/django/template/base.py:770: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  current = getattr(current, bit)

**Comment by reggieriser** [comment]
Thanks for the quick fixes, but it looks like there's still one lingering module_name usage on line 38 of change_form.html.  Still getting a deprecation there.

**Comment by darklow** [comment]
@reggieriser you're right, i don't know how i missed it, was searching multiple times :)
https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/change_form.html#L38
