### ISSUE TITLE
RemovedInDjango110Warning in suit_list_filter_select template tag

### ISSUE THREAD

**Issue by reggieriser** [darklow/django-suit#411]
I'm getting a RemovedInDjango110Warning when executing the suit_list_filter_select template tag with Django 1.8: "render() must be called with a dict, not a Context."

Looks like it's coming from this code in suit_list.py:

```python
    return tpl.render(Context({
        'field_name': field_key,
        'title': spec.title,
        'choices': choices,
        'spec': spec,
    }))
```

You no longer need to wrap the dictionary in a Context object for Django 1.8+.  Reference here:
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#get-template-and-select-template

**Comment by holms** [comment]
+1 would be nice to fix this :8ball:

**Comment by darklow** [comment]
Django Suit `bs3` brach or latest stable version?
