### ISSUE TITLE
Alphabet casing

### ISSUE THREAD

**Issue by s-monisha** [darklow/django-suit#420]
![casing o](https://cloud.githubusercontent.com/assets/13537847/9614144/714e6162-510d-11e5-9016-6b22b5b4dd2d.png)

In  Home » Bills » Quoted Order note
                             Quoted orders
alphabet O should in upper case.

**Comment by gamesbook** [comment]
I don't think Django works that way (camel-casing vs initial uppercase).  The docs are not quite clear on this; see:
https://docs.djangoproject.com/en/1.8/ref/models/options/#verbose-name
