### ISSUE TITLE
quick-search Error 403

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#421]
In admin page in top left show a search input to search users.
For admin works fine because these have permissions to all tables.
For users without permissions to auth/user tables return error 403.

If is a user without permissions into auth/user the search input should not be displayed.

**Comment by cubiczx** [comment]
For the moment hide search form in settings.py:
```python
SUIT_CONFIG = {
# Set to empty string if you want to hide search from menu
    'SEARCH_URL': '',
....
```

**Comment by SalahAdDin** [comment]
I have a problem with this too, will great that this option could integrate with a search backend as elasticsearch or woosh, but, i don't know how works admin search.

**Comment by cubiczx** [comment]
Thanks.
