### ISSUE TITLE
Admin actions labels Translation

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#423]
It is possible to translate the text that appears in the admin actions?
Changed "model" "object name"
Modified "model" "object name"
Deleted "model" "object name"

**Comment by cubiczx** [comment]
I solve with [django-suit-locale](https://pypi.python.org/pypi/django-suit-locale/) package

**Comment by SalahAdDin** [comment]
Yes, but, @darklow , will be great that you put localization files in this repo, not in external apps.
