### ISSUE TITLE
Error with AutosizedTextarea widget

### ISSUE THREAD

**Issue by Gustavosdo** [darklow/django-suit#426]
Hello guys,

I am using Django-Suit (0.2.14); Django (1.8.4).

At load my form, I get the error below in the browser console:
![error widget django](https://dl.dropboxusercontent.com/u/80415688/error-widget-django.PNG)

I did everything like the example in the documentation (I guess*):
http://django-suit.readthedocs.org/en/develop/widgets.html?highlight=autosized#autosizedtextarea

My code is similar to this:

        from suit.widgets import LinkedSelect, NumberInput, AutosizedTextarea
        from django import forms
        
        class MyForm(forms.ModelForm):
                ...
                class Meta:
                        model = MyModel
                        exclude = []
        
                        widgets = {
                                ...
                                'my_field': AutosizedTextarea(attrs={'rows': 5, 'class': 'input-xxlarge', 'placeholder': '...'}),
                        }
.

Pressing Ctrl + U, I see that jquery.autosize-min.js script is loaded correctly in the browser ...
![error widget django - ctrlU](https://dl.dropboxusercontent.com/u/80415688/error-widget-django-ctrlU.PNG)

Does anyone have any idea what it might be?

**Comment by Gustavosdo** [comment]
Sorry, I found the problem.

I am using Django-Selectable, and adding the above code on base_site.html file is causing the problem occurs.

    {% block extrahead %}
        {% load selectable_tags %}
        {% include_ui_theme %}
        {% include_jquery_libs %}
    {% endblock %}

**Comment by SalahAdDin** [comment]
:+1:  thanks for you advice.

**Comment by Gustavosdo** [comment]
I believe the django-suit support this library would be interesting.

**Comment by Gustavosdo** [comment]
Hello guys,

A while ago I posted this question. I will leave here the solution found to the problem.

Simply overwrite the jquery-js.html file found in the django-selectable library and remove the call jquery.min.js.

For example:

`{# {% if version %}<script src="//ajax.googleapis.com/ajax/libs/jquery/{{ version }}/jquery.min.js"></script>{% endif %} #}`
`{% if ui %}<script src="//ajax.googleapis.com/ajax/libs/jqueryui/{{ ui }}/jquery-ui.js"></script>{% endif %}`


As the django-suit already contains a version of the library, everything will work correctly.
