### ISSUE TITLE
Hide specific users from auth user model for non super users

### ISSUE THREAD

**Issue by cubiczx** [darklow/django-suit#429]
I need hide a super admin's users from auth user model of Django of list users template for a normal users or no super admin users.

**Comment by darklow** [comment]
This is not related to django-suit in any way.
You should ask this on django repository or use google or StackOverflow.

**Comment by SalahAdDin** [comment]
Amigo, busca en internet como dar o quitar permisos a usuarios y como restringir el acceso de usuarios al modelo, esto tiene que ver con django-admin.

**Comment by cubiczx** [comment]
Ya lo he resuelto sobreescribiendo la clase UserAdmin de model.ModelAdmin:

```python
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from django.core.exceptions import PermissionDenied

class UserAdmin(admin.ModelAdmin):
# Hide super user for no super user's (Pre-populating data)
    def queryset(self, request):
        if request.user.is_superuser:
            return User.objects.all()
        return User.objects.filter(is_superuser=False)
```

**Comment by SalahAdDin** [comment]
Exacto amigo, así es como se hace, cualquier apunte me preguntas :D
