### ISSUE TITLE
Vertical vs Horizontal menu

### ISSUE THREAD

**Issue by Jzarecta** [darklow/django-suit#434]
I am not able to switch between horizontal top nav bar to a vertical one. Most of the examples have vertical, but  my default showed as horizontal. Is there any way to get the vertical one. I read the Menu configuration but none of the variables suggested they will change that property. 
http://i.imgur.com/2NIoRE6.jpg

**Comment by darklow** [comment]
You're using alpha version of Django Suit which is not complete and it has only horizontal menu.
If you want to use vertical menu you should use stable version as Documentation says:
http://django-suit.readthedocs.org/en/develop/#installation
