### ISSUE TITLE
关于在CrazyEye管理后台中批量任务的创建

### ISSUE THREAD

**Issue by xiudadadeyumi** [darklow/django-suit#453]
大家好：
      最近搭建一个CrazyEye环境，准备测试下，看看性能如何？我登录它的管理后台，在“批量任务”中，发现只能查询任务，而无法创建任务。而且在“审计日志”中，只能查询到用户的登陆信息，而无法查阅更为详细的信息，比如用户在哪台服务器执行了哪些命令，修改过什么配置文件等，求指点。

**Comment by SalahAdDin** [comment]
Put here your question in english please.

**Comment by xiudadadeyumi** [comment]
Everybody is good:
Recently set up a CrazyEye environment, ready to test, see how the performance?I log in it management background, in the "batch task", found that only the query task, to create a task.And in the "audit log", can only query to the user login information, to refer to more detailed information, such as user where the server what command, modify any configuration files, etc., ask for advice.
