### ISSUE TITLE
Django 1.9 updated admin urls: broken links (history)

### ISSUE THREAD

**Issue by infinityxxx** [darklow/django-suit#457]
Example can be found here: `suit/templates/admin/change_form.html` and in other files too.
```
<li>
  <a href="history/" class="historylink">
      <i class="icon-time icon-alpha75"></i>{% trans "History" %}
  </a>
</li>
```

https://docs.djangoproject.com/en/1.9/releases/1.9/#django-contrib-admin

**Comment by infinityxxx** [comment]
All broken links can be fixed in this manner:

```
<li>
  {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
  <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
</li>
```

https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_form.html#L31

**Comment by infinityxxx** [comment]
You can also add same changes here:

https://github.com/darklow/django-suit/blob/19151b7ae21b7bca6889f41cce3362c142700597/suit/templates/admin/filer/folder/change_form.html#L33

https://github.com/darklow/django-suit/blob/19151b7ae21b7bca6889f41cce3362c142700597/suit/templates/admin/cms/page/change_form.html#L105

https://github.com/darklow/django-suit/blob/19151b7ae21b7bca6889f41cce3362c142700597/suit/templates/admin/filer/image/change_form.html#L9

**Comment by infinityxxx** [comment]
By the way, hardcoded `<a href="history/" class="historylink">` appearances in django admin templates have been replaced since Django 1.5 version. If you discontinue support of Django 1.4, you can get rid of if/else in templates.

**Comment by darklow** [comment]
Fixed in https://github.com/darklow/django-suit/pull/467 https://github.com/darklow/django-suit/pull/468
