### ISSUE TITLE
Django 1.9 updated admin urls: broken links (add) 

### ISSUE THREAD

**Issue by infinityxxx** [darklow/django-suit#459]
Links for adding elements should be updated since admin urls changed in Django 1.9 (see https://docs.djangoproject.com/en/1.9/releases/1.9/#django-contrib-admin)

Here add-link is broken:
https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/change_form.html#L119 

And probably better replace hardcoded links everywhere:
https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/cms/page/change_list.html#L113 (still working)

https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/cms/page/change_list.html#L139 (still working)

https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/cms/page/change_form.html#L108 (broken)

**Comment by uolter** [comment]
Here delete links are also broken:

https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/submit_line.html

https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/page_submit_line.html

same reason same fix as above.

**Comment by saxbophone** [comment]
The delete links have been fixed in the issue tagged above (#466)

If someone hasn't already picked up this issue for fixing the add links, I could probably do that tomorrow as it's very similar.

**Comment by darklow** [comment]
Issue #466 is already merged in.
Sure, it would be great if you could take a look in this issue as well.
Thank you
