### ISSUE TITLE
Django 1.8 NoReverseMatch error in suit/templatetags/suit_menu.py

### ISSUE THREAD

**Issue by Pavel1996** [darklow/django-suit#460]
I use custom AdminSite, and it does not work with NoReverseMatch error. In function get_admin_site You use func_closure attribute of resolver_match.func, but it is deprecated maybe. My code works only I use \__closure__ attr instead.

**Comment by KFoxder** [comment]
+1 there is a PR open here to fix this. https://github.com/darklow/django-suit/pull/476

**Comment by darklow** [comment]
Merged in #485
