### ISSUE TITLE
Pages admin looks weird, looks to have a few different CSS then the demo

### ISSUE THREAD

**Issue by altryne** [darklow/django-suit#461]
Hey guys,
Trying to install the suit admin, and removed the "django-admin-stlye" that I had previously.
Still the `pages` page looks like this 
![image](https://cloud.githubusercontent.com/assets/463317/12016546/ef9d945e-ad54-11e5-8a65-ce43b3b5c29c.png)

and not like it looks in the demo

Also, a lot of the buttons don't have the `btn` classes on them making them look like links.

What am I missing?

**Comment by darklow** [comment]
Please read my comment regarding newest django-cms and support for it:
#213 (comment)

**Comment by altryne** [comment]
Thanks! 
I'd just add that it's very sad that there's no support, we were ready to pay for a license and everything. 

And I'd wish the main django-suit site had a version near the place where it says it supports django-cms, django-filer etc' so we could know in advance that it's not a correct fit for our current project.

Thanks anyway
