### ISSUE TITLE
Poll - Please post what version of suit are you using

### ISSUE THREAD

**Issue by darklow** [darklow/django-suit#463]
To better understand which way to move from this point, I would be thankful if you would post in comments what version of Django Suit (options 1 or 2) and Django are you using in recent projects. Feel free to add any notes as well. Thanks.

1. 0.2.x - Classic UI
2. 0.3a - Bootstrap 3 alpha version
With which Django versions

**Comment by nchampsavoir** [comment]
0.2.x - Classic UI. Mostly because the project I'm working on started two years ago and 0.3 wasn't available at the time.

**Comment by parijathakumar** [comment]
I am currently using 0.2.x as it is mentioned that "BS3 branch is considered as alpha version and is not yet ready for production use". But there are a lot of shortcomings in 0.2.x branch though. For me the deal breakers for 0.2.x branch are "no horizontal layout of 'save' buttons block", "no hiding of left menu-bar" both of which waste a lot of space in my current project.
In fact, I am daily checking github and your twitter updates too for any updates on the bs3 branch so that I can immediately switch to it.

**Comment by darklow** [comment]
@parijathakumar Thanks for your feedback.

I am starting to make two large projects which will need django suit, so once and for all I want to finish the next version and go with one single branch again. 

Now after using a while both versions stable and bs3 i can see benefits and cons of both - in terms of usability and maintenance as well (maintaining Django changes and third party libs)

I can't deny fact that original Django admin is getting little prettier but still far from perfect. Now I am still looking for ways to make following Django admin template updates less painful. One thing for sure - Django Suit won't be able to support all the Django versions starting from 1.4 so I am also deciding best way of compatibility policies. Maybe latest version of suit would support two latest versions of Django or something like that.

I am also exploring some client side JS DOM manipulations instead of server-side ones.
Just take a look here: https://github.com/darklow/django-suit/blob/bs3/suit/widgets.py
All the effort that is needed to be done to make widgets a little nicer. And once there are changes in Django original admin, there is a big chance something will break in Django Suit as well.

Just some thoughts out loud.

**Comment by rouxxx** [comment]
0.2.x - Classic UI with django 1.7.8

I didn't play with 0.3a yet.

The main point that took me time was to add a custom dashboard page but finally made it (https://github.com/darklow/django-suit/issues/409). I think it can be embedded into django-suit, it would be a real advantage compared to other admin themes.

**Comment by SalahAdDin** [comment]
0.2.X - Classic UI with Django 1.9.1

**Comment by gamesbook** [comment]
0.2.x

**Comment by alexPerezLillo** [comment]
0.2.x

**Comment by AliPolat** [comment]
0.2.15 and waiting for 0.3

**Comment by mauriciobaeza** [comment]
0.2.16

**Comment by darklow** [comment]
This was a survey to decide should i continue bs3 branch or start fresh.
Since development of v2 has already started (see #475), closing this issue.
