### ISSUE TITLE
Missing PNG/GIF icons in Django 1.9

### ISSUE THREAD

**Issue by saxbophone** [darklow/django-suit#469]
In Django 1.9, PNG and GIF admin icons were [replaced with SVG icons](https://docs.djangoproject.com/en/1.9/releases/1.9/#contrib-admin-browser-support) (and therefore breaking IE8 compatibility, which Django now consider to be at end-of-life).

This causes missing icons to be displayed in the admin for icons that are referenced by path. The only one of these I have been able to find so far is `/static/admin/img/icon-unknown.gif` but I'm sure there are more of these that have been affected.

I guess this one might pose a bit of an issue if this project still supports IE8 although a simple fix could be to carry on with the `if django_version < 1.9` pattern as in similar issues.

**Comment by parijathakumar** [comment]
+1. 

Pl see a picture below ...

![screenshot from 2016-01-22 11-09-30](https://cloud.githubusercontent.com/assets/883045/12503261/cb102630-c0f8-11e5-88b3-dac8ad7f0189.png)

There may be more.

**Comment by hickeroar** [comment]
+2

Also ran into this issue in several places in the admin panel.

**Comment by mbrownGraham** [comment]
Having this issue in 1.8. When inspected, I see (/adminimg/icon-unknown.gif) missing slash

**Comment by tctimmeh** [comment]
+1

In places where it previously showed a "?" icon with DB field help text as a hint, there is now a broken image icon and the field help text, which could be a lot of text where a tiny icon should be. It is most evident on admin inlines for models which have help_text.

**Comment by francisco-elements** [comment]
+1 to this, it's quite annoying to replace the icons with big ALT texts, as @tctimmeh pointed out.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by barklund** [comment]
+1

When using Whitenoise for serving the static files, the whole inline / form doesn't render due to errors - which is an even bigger issues than just being annoying.

`ValueError: The file 'admin/img/icon-unknown.gif' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x7f9ddd1748d0>.`

**Comment by darklow** [comment]
The only place where I see referenced any `icon*.gif` is in tabular inline.
https://github.com/darklow/django-suit/blob/develop/suit/templates/admin/edit_inline/tabular.html#L14

Am I right? 
And you all are seeing empty icon in tabular inline only?

**Comment by darklow** [comment]
@barklund I would be glad to fix, but I have no clue yet how. Looks like whitenoise is just using pattern match for all {% static %} tags. So even if I will use conditional check for Django version and include either `{% static "admin/img/icon-unknown.svg" %}` or `{% static "admin/img/icon-unknown.gif" %}` whitenoise now will try to collectstatic both files.

**Comment by barklund** [comment]
@darklow css the icon like all other icons in the admin? Everything else works fine except this single icon out of a seemingly pretty large set.

**Comment by rebkwok** [comment]
@darklow
I also had this issue.
The FilteredSelectMultiple widget is generated by js; it adds the classes for the help and search icons https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/django/contrib/admin/static/admin/js/SelectFilter2.js#L50
https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/django/contrib/admin/static/admin/js/SelectFilter2.js#L68

The help and search icons are in django css; I got them to show up by adding the following to my css:
```
.selector .help-icon {
    background: url(../admin/img/icon-unknown.svg) 0 0 no-repeat;
    display: inline-block;
    vertical-align: middle;
    margin: -2px 0 0 2px;
    width: 13px;
    height: 13px;
}

.selector .selector-chosen .help-icon {
    background: url(../admin/img/icon-unknown-alt.svg) 0 0 no-repeat;
}

.selector .search-label-icon {
    background: url(../admin/img/search.svg) 0 0 no-repeat;
    display: inline-block;
    height: 18px;
    width: 18px;
}
```

**Comment by mord4z** [comment]
I fixed this issue by coping to my static js folder and editing the Django SelectFilter2.js, added these lines:
if (typeof admin_static_prefix == 'undefined'){
            admin_static_prefix = 'http://'+location.host+'/static/admin/';
        }

Note that this is just a temporary workaround

**Comment by mathieuhinderyckx** [comment]
Any update on this?
