### ISSUE TITLE
bootstrap3 css classes

### ISSUE THREAD

**Issue by behnejad** [darklow/django-suit#472]
i have this problem since i start using branch bs3
does it support any of these classes?
`warning`, `error`, `info` 

the part of the code i'm using for rows css class in admin.py
```
def suit_row_attributes(self, obj, *args):
        return {'class': (('warning', 'error'), ('success', 'info'))[obj.isactivate][obj.ban]}
```
![screenshot from 2016-01-28 09-35-51](https://cloud.githubusercontent.com/assets/3690943/12636732/78af375e-c5a4-11e5-8606-b690ca0d6308.png)

**Comment by darklow** [comment]
Can you take a look and see if there are class names added to `TR` elements?

**Comment by behnejad** [comment]
yes, classes successfully added to `TR` element but as you see in the picture `error` class has problem.
![screenshot from 2016-01-29 16-19-21](https://cloud.githubusercontent.com/assets/3690943/12676049/447207ae-c6a4-11e5-9022-2f0ff2bb039b.png)

and i think it's better if you increase the opacity of `warning` class.

**Comment by darklow** [comment]
That is the side-effect of bootstrap 3, there is no more `error` class in bootstrap.
Try using `danger` instead
http://getbootstrap.com/css/#tables-contextual-classes

**Comment by behnejad** [comment]
You are right.
and another question:
in the last picture, is there any way to add a css class to models label (E.x. Users) in `adminModel` class? 
or I should add my css class to the `li` tag manually.
