### ISSUE TITLE
Date and Datetime field not show calendar

### ISSUE THREAD

**Issue by gibosler** [darklow/django-suit#481]
Django 1.9.2 but i've tried to downgrade, i've the same issue.
On DateField i can see the "today" link and the calendar ICON but on click not show calendar. 
I've tryed with and without Suit widget with the same result. Disabling suit it works normally.

![image](https://cloud.githubusercontent.com/assets/17119871/12881870/8caa9e54-ce4d-11e5-9a27-66ac363eed69.png)

![image](https://cloud.githubusercontent.com/assets/17119871/12881883/9f74b8bc-ce4d-11e5-9f8c-01186bece391.png)

The html is loaded correectly but the JS is not "clickable" on the icon. if i call openCalendar() it works.
![image](https://cloud.githubusercontent.com/assets/17119871/12881905/c8fe452c-ce4d-11e5-97be-46f3a6f2307a.png)

**Comment by darklow** [comment]
To what Django version you tried downgrading?

**Comment by gibosler** [comment]
1.7.9 or 1.8

**Comment by mauriciobaeza** [comment]
Confirm this bug with Django 1.9.2 and Suit 0.2.16

Best regards

**Comment by jamescw** [comment]
Having the same issue site wide after upgrading to Django 1.9

**Comment by martinjobb** [comment]
Happens to me too (Django 1.9.2 and Suit 0.2.16)

**Comment by tirnovali** [comment]
Same problem (Django 1.9.2 and Suit 0.2.16)

**Comment by dimddev** [comment]
I got the same problem with these versions:
Django==1.9.3
django-suit==0.2.17

**Comment by darklow** [comment]
Just releases new `0.2.18` version with fixes for this issue
```
pip install -U django-suit
``

**Comment by tirnovali** [comment]
just make pip update and collectstatic however calendar icon not shown already

**Comment by darklow** [comment]
Can anyone else give some feedback?
I tested it on Django 1.9.1 and 1.9.3 versions and it works for me.
@tirnovali By inspect - do you see extra css added for `.date-icon, .clock-icon` classes?

**Comment by parijathakumar** [comment]
Problem is solved for me. I am on django 1.9.3 and suit 0.2.18. Thank you.

**Comment by mauriciobaeza** [comment]
Now work fine: 
Django==1.9.3
django-suit==0.2.18

Thanks

**Comment by darklow** [comment]
@tirnovali Others are reporting it working too.
Please try hard reload, maybe browser cache issue.

**Comment by tirnovali** [comment]
@darklow store my static files at S3 and the versions are
Django==1.9.3
django-suit==0.2.18

but the calendar icons not shown

**Comment by darklow** [comment]
@tirnovali 
1) Do you use SuitDateWidgets or original django admin dates widgets?
2) Open Chrome Dev Console  > Network and select Disable Cache and try again
3) Try using on local Debug=True and Django built int `./manage.py runserver` then you'll be sure it is not collectstatic or s3 related caching problem.
4) By CSS inspect - do you see extra css added for `.date-icon`, `.clock-icon` classes?

**Comment by leench** [comment]
@darklow 
in ./manage.py runserver
User original django admin dates widgets.
Disabled Cache.

Django==1.9.5
django-suit==0.2.18

In suit.css file, I can found `.date-icon` and `.clock-icon` classes.
but in CSS inspect, I can not found them.

![suit](https://cloud.githubusercontent.com/assets/157350/14404348/d9410306-fea5-11e5-8079-7836b73d4880.png)

**Comment by darklow** [comment]
@leench What is your question or statement?
Please post also how do you use this field: in admin.py or inlines etc. 
`admin.py` definition would be best.

**Comment by leench** [comment]
@darklow 
Same as top problem, do not show date and clock icon.

field:
`pub_date = models.DateTimeField(_('pub date'))`

admin.py doing nothing:
```
class ArticleAdmin(admin.ModelAdmin):
    pass

admin.site.register(Article, ArticleAdmin)
```

**Comment by jerzyk** [comment]
django 1.9 to 1.9.6, plain installation with just only django-suit - no changes to config/setting - shows no icon (like first picture on initial ticket) 1.8.13 - shows calendar/clock icon

this is with no change to admin (original admin widgets)

**Comment by jerzyk** [comment]
maybe small addition to the docs? mokeypatching admin - add this to `__init__.py` to your 'main' project module:
```
import suit.widgets
from django import forms
from django.contrib.admin.options import FORMFIELD_FOR_DBFIELD_DEFAULTS
from django.db import models

FORMFIELD_FOR_DBFIELD_DEFAULTS.update({
    models.DateTimeField: {
        'form_class': forms.SplitDateTimeField,
        'widget': suit.widgets.SuitSplitDateTimeWidget
    },
    models.DateField: {'widget': suit.widgets.SuitDateWidget},
    models.TimeField: {'widget': suit.widgets.SuitTimeWidget},
})
```

**Comment by tiagovaz** [comment]
I can confirm that using the code above from @jerzyk was the only way to get the widget working here. 

django-suit 0.2.18
django 1.9.6

**Comment by DjThopson** [comment]
Well im have Django 1.9.8 and Suit 0.2.21 and dont works, someone suggestion? 
Thanks

**Comment by neilhepburn** [comment]
FYI I can confirm same effect - no widgets on date/time fields. 

When I apply the jerzky/May 7 monkeypatch they are there.  Good for now. 

Django==1.10.2
django-suit==0.2.21

Thanks!

**Comment by DjThopson** [comment]
Well finally i finished the repair the bug: 

i overwrite the DateTimeShortcuts.js archive into ... /env/lib/python3.4/site-packages/django/contrib/admin/static/admin/js/admin/ in the line 221.

old:
quickElement(
                'span', cal_link, '',
                'class', 'date-icon',
                'title', gettext('Choose a Date')
            );
new:
quickElement(
                'img', cal_link, '',
                'src', '/static/admin/img/icon_calendar.gif',
                'alt', gettext('Calendario')
            );

That works for me with Django 1.9.8 and Suit 0.2.21.
