### ISSUE TITLE
MPTT Bug in bs3 

### ISSUE THREAD

**Issue by kira8565** [darklow/django-suit#483]
I Use MPTT in  Django-Suit BS3 Version but has Some Problem like This
![qq20160214-0](https://cloud.githubusercontent.com/assets/4230340/13033986/7f9a811e-d363-11e5-959f-f08b1bc58c50.png)

But in 0.2.16 is ok
![qq20160214-1](https://cloud.githubusercontent.com/assets/4230340/13033993/a9131074-d363-11e5-902c-d18d23ba2559.png)

**Comment by darklow** [comment]
Bs3 version was never completed and has been discontinued by now. It never had any 3rd party app support. Read this issue about next big release - v2: https://github.com/darklow/django-suit/issues/475
