### ISSUE TITLE
Pagination dots shown as plain HTML

### ISSUE THREAD

**Issue by lukas-schulze** [darklow/django-suit#486]
In one of my projects, the django suit does display plain HTML tags in the pagination.

I use Django 1.9.1 and django-suit 0.2.15.
I also tried uninstall and reinstall of the django-suit via pip.

Any ideas?

![unspecified](https://cloud.githubusercontent.com/assets/820580/13352028/e1a36350-dc8a-11e5-8ceb-04e15f905dce.png)

**Comment by darklow** [comment]
Sorry cannot replicate. 
Tried Django 1.9.1 and also latest Django 1.9.3.
I doubt it will help, but try upgrading django-suit to latest version `0.2.17`.

Here is the code that that specific part of html as safe:
https://github.com/darklow/django-suit/blob/develop/suit/templatetags/suit_list.py#L36
You can try do some debugging.

**Comment by lukas-schulze** [comment]
Now I can't reproduce it either.
