### ISSUE TITLE
Admin: delete link on model change pages is broken (404)

### ISSUE THREAD

**Issue by hchokshi** [darklow/django-suit#489]
A 404 error occurs when clicking the "delete" link on any model's change page. The link takes me to ```/admin/APPNAME/MODELNAME/1234/change/delete/```. The expected behaviour is to go to ```/admin/APPNAME/MODELNAME/1234/delete/```. Manually changing the URL to this works fine.

I believe the issue is caused here https://github.com/darklow/django-suit/blob/master/suit/templates/admin/submit_line.html#L10 as a result of version comparison not being done correctly. For example, in my project it would be evaluated as ```{% if 1.9.1 < 1.9 %}```, and this is coming out as true.

I'm using Django version 1.9.1 and the issue occurs in both local debugging (runserver) and production. Python 2.7.10 is used in both environments. Being aware of my project environments, I can remove the IF and use only the 1.9 onwards piece of code by overriding the template and only using https://github.com/darklow/django-suit/blob/master/suit/templates/admin/submit_line.html#L13

**Comment by darklow** [comment]
I just tried `Django 1.9.1` and everything works fine for me.
Are you sure you're using latest Django Suit version `0.2.18`?

**Comment by hchokshi** [comment]
Sorry! It turns out our project was on a slightly outdated version of django-suit (0.2.15). Upgraded to 0.2.18 and it's fine! Thanks.
