### ISSUE TITLE
using <script> ... </script> broken css ?

### ISSUE THREAD

**Issue by emper0r** [darklow/django-suit#492]
Hi, it's possible the < script > tag broke the css of django-suit?

i'm trying to implement a little dashboard using http://netdata.firehol.org/
according to wiki, i can use it with < script type="text/javascript" src="http://localhost:19999/dashboard.js" ></script>
but the left-nav for menus of django-suit lost the position when I use it.... how can i solve this?

using the new dashboard live
![broking_left-nav](https://cloud.githubusercontent.com/assets/819042/13980049/8071a4d2-f0dc-11e5-877c-b876807b926d.png)

without script and using a simple < img > in this case mrtg works fine.
![img_mrtg](https://cloud.githubusercontent.com/assets/819042/13980084/cc331c48-f0dc-11e5-83fc-3441d65300bf.png)

i'm trying to use < span > or another < div > trying to override this error but nothing...  :|

a snippet here: https://dpaste.de/1D67

**Comment by darklow** [comment]
Looks like `dashboard.js` injects some inline styles which override django-suit menu styles. 
You'll have to compare resulting CSS for both views and override manually to set it back to original.

**Comment by emper0r** [comment]
Hi, thanks for a quick response, in fact, i see when i wrote the code, I lost the colors, and I must put this to override again to get back the css from django-suit

on the code with dashboard live... inserting this lines i can recovery from blue to my red style:

'< link rel="stylesheet" type="text/css" href="/static/suit/bootstrap/css/bootstrap.min.css"/>'
'< link rel="stylesheet" type="text/css" href="/static/suit/css/suit.css" media="all">'

those lines are from the mrtg view on comparasion. but not appears anithyng about left-nav css...
maybe inserting here another links for the left-nav ? what lines must be?

**Comment by darklow** [comment]
It will be impossible to paste all styles here.
But you can use Chrome or Firefox console to see resulting CSS and where each style definition comes from.
For example:
![image](https://cloud.githubusercontent.com/assets/445304/13980742/c51d8338-f0e8-11e5-82ed-5dee566a40d0.png)

**Comment by emper0r** [comment]
Ok, I keep trying , thanks

**Comment by emper0r** [comment]
ok, found it!!.... 
need override suit.css: 9
#suit-left {
    width: 200px;
    right: 240px;
    margin-left: -94%;  (before -100%) just moving 6px
}
