### ISSUE TITLE
v2 form_size customization issue

### ISSUE THREAD

**Issue by joseph2002** [darklow/django-suit#500]
By reading the code, I have to write something like this to customize the size of some kind of widgets:
```python
class SuitConfig(apps.DjangoSuitConfig):
   form_size = {
        'default': apps.SUIT_FORM_SIZE_SMALL,
        'widgets': {
            ' widget-AdminURLFieldWidget': apps.SUIT_FORM_SIZE_LARGE,
            ' widget-AdminTextareaWidget': apps.SUIT_FORM_SIZE_LARGE,
        },
    }
```
is it desired or bug?

**Comment by darklow** [comment]
Docs are not ready therefore let me explain how it works.
Form sizing can be controlled by `form_size` or `suit_form_size` parameter in two levels.
1. Global config in `apps.py` using `form_size` parameter.
2. Per `ModelAdmin` using `suit_form_size` parameter

`form_size` is a dictionary which can be configured with three keys:
1. `default` - sets default form sizing
2. `fieldsets` - dictionary of sizing overrides per whole fieldset
3. `fields` - dictionary of sizing overrides per each field
4. `widgets` - dictionary of sizing overrides per widget class name.

About values - If you are familiar with bootstrap 3+ you'll know that in responsive selectors you must use `col-xs-12 col-sm-6` etc. type of css classes to control column width. This is what `DjangoSuitConfig. SUIT_FORM_SIZE_LARGE ` constants are, these are just constants - combinations of label column versus field column proportions.

See all constants here:
https://github.com/darklow/django-suit/blob/v2/suit/apps.py

Finally here is an example of using all keys for `suit_form_size`:
```py
from suit import apps

class MyModelAdmin(admin.ModelAdmin):
    suit_form_size = {
        # You can either use constants from `apps.SUIT_FORM_SIZE...` 
        # or manual tuple using two items - first for label columns, second for field column
        'default': ('col-xs-12 col-sm-2', 'col-xs-12 col-sm-10'),
        'fields': {
             'field_name': apps.SUIT_FORM_SIZE_LARGE,
             'field_name2': apps.SUIT_FORM_SIZE_X_LARGE,
             'country_code': apps.SUIT_FORM_SIZE_INLINE
         },
         'widgets': {
             'AdminTextareaWidget': apps.SUIT_FORM_SIZE_FULL,
             'AutosizedTextarea': : apps.SUIT_FORM_SIZE_XXX_LARGE,
         },
         'fieldsets': {
             'fieldset_name': apps.SUIT_FORM_SIZE_FULL,
             'fieldset_name2': apps.SUIT_FORM_SIZE_FULL,
         }
    }

```

You can also see few examples how I use it in demo app code which is included with v2.
https://github.com/darklow/django-suit/blob/v2/demo/demo/admin.py

**Comment by joseph2002** [comment]
I mean I can only got this to work with
```python
'widgets': {
            ' widget-AdminURLFieldWidget': apps.SUIT_FORM_SIZE_LARGE,
            ' widget-AdminTextareaWidget': apps.SUIT_FORM_SIZE_LARGE,
},
```
instead of 
```python
'widgets': {
            'AdminURLFieldWidget': apps.SUIT_FORM_SIZE_LARGE,
            'AdminTextareaWidget': apps.SUIT_FORM_SIZE_LARGE,
},
```

**Comment by joseph2002** [comment]
I think this is because you get widget_class_name by this function in suit_form.py:
```python
def get_form_class(field, fieldset, idx):
    ....
    # Detect widget class
    widget_class_name = suit_form_field_widget_class(field)
   ...

def suit_form_field_widget_class(field):
    try:
        widget_class_name = field.field.widget.__class__.__name__
        return ' widget-%s' % widget_class_name
    except AttributeError:
        return ''
```

**Comment by darklow** [comment]
Yep, apparently this is a bug after recent refactoring. I mixed css class with class.
Fix is on it's wat

**Comment by joseph2002** [comment]
Thanks and by the way, could you provide a setting that gives a fixed width submit column if form_submit_on_right-True.
It is too wide on a FHD display and looks ugly.

**Comment by darklow** [comment]
I fixed the bug with widgets. Now you don't need `widget-` prefix anymore.
To me form submit on right on FHD display looks great and not too wide.
Can you provide a screenshot?
Anyway I don't think such a thing requires a parameter.
You can always use CSS for that. Use following css to override default values. Just change a percentage width for right column and left column will adjust accordingly.
```css
.body.change-form.suit_form_submit_on_right .edit-row > div.col-right {
  width: 15%; 
}
``

**Comment by joseph2002** [comment]
got it, thanks
