### ISSUE TITLE
feature request:  persistent filters (in the header?)

### ISSUE THREAD

**Issue by ed4g** [darklow/django-suit#503]
It would be nice to be able to move from object to object and continue to respect the same filter, perhaps something selected in the header. Many objects require the same filter, and users would be working in the "context" of that filter in large part, for one of our several apps. It will be painful for them to have to refilter each screen with the same filter every time upon entry.

**Comment by darklow** [comment]
I think this is very "narrow" and local feature too to be implemented in Django Suit. In 5 years working with Django admin Django admin and tons of Django app admins never had even a slight wish to have filters that are persistent over multiple apps or models.

**Comment by ed4g** [comment]
Thank you for considering this, I appreciate it.
