### ISSUE TITLE
feature request:  chained filters

### ISSUE THREAD

**Issue by ed4g** [darklow/django-suit#504]
I've looked everywhere but haven't found any filters which rely on other filters in django admin.  The classic case is a car shopping app, where you have to select the make first and then the models show up. The real problem comes if you select the make but then still get all models for all makes!

Is this something that could be achieved in suit or would it need to kick down to admin?

Thanks for your consideration,

Ed

**Comment by darklow** [comment]
Currently this is not possible and it is out of future scope too. 
Personally I don't think such feature is necessary. You're comparing two different things - customers in shop who doesn't know what they want and users in admin who are looking for something specific, so I don't see big benefits of the feature.
I believe it is possible and not so hard to make it too, but I don't think such feature is needed, there are much more useful features we can spend time on :)

**Comment by gamesbook** [comment]
@ed4g You can use django-selectable; they provide integration with the admin - see http://django-selectable.readthedocs.io/en/v0.9.-/admin.html (interestingly, they also support Grappelli... maybe you can ask them to consider support django-suit as well?)

**Comment by ed4g** [comment]
I took a look and smart-selects seems more like an autocompleter  (they do talk about chaining filters but I think you have to write javascript??)    

Anyway I think I'm closing in on the ability to do this, slowly.  If I figure it out I'll post it here or anywhere else that is useful.  IMO it is needed for any complex data model when you in the context of one model, and other models should be constrained for appropriateness by going "up and around" the relationship hierarchy. Without this, many model screens are simply broken as they allow choosing inappropriate relations.

**Comment by ed4g** [comment]
btw I have extended my reply beyond chained filters because what I really need is "chained everything" - sorry if that was unclear.  This guy appears to have needed and achieved the same thing several years ago:

http://schinckel.net/2011/07/20/filtering-querysets-in-django.contrib.admin-forms/

**Comment by EOSIT** [comment]
@ed4g I am not sure you are looking at the same app?  I have used to do exactly what you originally asked for; no javascript required (in the admin, that is).  I use a different app for autocomplete.

**Comment by ed4g** [comment]
I think you are right EOSIT, I don't know what the heck I was looking at the first time around. 

In the meantime, I've been able to add context filters to change pages and inlines as well, but haven't hit the primary filters yet and I don't think I will be able to chain a dropdown to another dropdown, so it looks like I will need to use smart selects one way or another. Thanks EOSIT and gamesbook for pointing this out.

**Comment by mj-v** [comment]
@darklow We are suffering, needing this option. for example you want to filter or add in forms countries/cities which are related to each other, and imagine it's huge list. then ppl need this functionality.

**Comment by pydatageek** [comment]
I think, the functionality mentioned here should be one of the default ones in a web framework. Django itself should have it. For now, django doesn't have it so I would like suit would bring it into action by default instead of hacking or using additional apps.
