### ISSUE TITLE
Unable to set url by name at MENU settings

### ISSUE THREAD

**Issue by inoks** [darklow/django-suit#506]
It will be great to have ability to specify `url` by `name`, defined in `urls.py`.
```
SUIT_CONFIG = {
    'MENU': (
        {
            'label': 'Feedback',
            'url': 'app:feedback'
        },
...
}

```

**Comment by darklow** [comment]
You can, but you must provide valid argument for resolve method.
https://github.com/darklow/django-suit/blob/develop/suit/templatetags/suit_menu.py#L474

**Comment by inoks** [comment]
@darklow Thanks, it was my fault. It works!

**Comment by SalahAdDin** [comment]
@inoks please, put you example here :D

**Comment by darklow** [comment]
@SalahAdDin and @inoks 
Btw it is also documented:
http://django-suit.readthedocs.io/en/develop/configuration.html#id1

From docs:

``url`` parameter can be:

* Absolute url like ``/custom/``
* Named url like ``admin:index``
* Model name like ``auth.user`` to make link to model changelist
* If ``MENU_OPEN_FIRST_CHILD=True`` and models for app exists, you can skip ``url`` key
* If you add key ``'blank': True`` links will open in new window

**Comment by inoks** [comment]
@SalahAdDin It was totally my fault - wrong app name was used in url, sorry for false alarm :( 
And thanks to everyone for fast response!
