### ISSUE TITLE
list editable width

### ISSUE THREAD

**Issue by jiujitsu** [darklow/django-suit#507]
Is there any way I can make `list_editable` fields, specifically when they are of type `select`, take up the minimum amount of width? Screenshot here to show what I mean: http://puu.sh/p30wo/0d2266555d.png.

Ideally the select box would only be as wide as the longest element inside of it.

**Comment by darklow** [comment]
Target your select elements with CSS selectors and set `width: auto`. Use `!important` if needed. However long element text can stretch your select too wide. You can also try using for example `max-width:90%` to avoid that.
