### ISSUE TITLE
CSS not applied to admin panel.

### ISSUE THREAD

**Issue by RLJMedia** [darklow/django-suit#508]
Hello Group,

I finally got the admin panel sort of working. The css does not seem to be applied. Any clues?

I created a demo user

user: demo
password: demo

http://162.243.201.237/admin

![screen shot 2016-06-01 at 11 27 11 am](https://cloud.githubusercontent.com/assets/1318220/15715271/d4137c78-27eb-11e6-9408-115fa2d43576.png)

**Comment by darklow** [comment]
How did you installed Django Suit?
What command you used to run Django?
Keep in mind you must run `collectstatic` if you're running Django though webserver: 
http://django-suit.readthedocs.io/en/develop/#deployment

**Comment by RLJMedia** [comment]
I followed these instructions:
[(http://django-suit.readthedocs.io/en/develop/)]
I did run collectstatic 
OH: the only thing I did not do was DEBUG = False. I get a 400 message on the site when I do that.

**Comment by darklow** [comment]
What command you used to run Django?

**Comment by darklow** [comment]
You are serving Django with nginx, therefore you must server static files by yourself:
https://docs.djangoproject.com/en/1.9/howto/static-files/

CSS file is not found:
http://162.243.201.237/static/suit/css/suit.css

**Comment by RLJMedia** [comment]
The server is setup with Django, 1.6, Ngnix , Postgres.

I did not run the  server with this command: python manage.py runserver

**Comment by RLJMedia** [comment]
I thought that is what the collectstatic  does?

**Comment by darklow** [comment]
Collectstatic command only collects all static files from all Django apps and copies into one location.
You must take care of serving them on your own using nginx.
Django serves static files only in development mode using runserver if DEBUG = True

**Comment by RLJMedia** [comment]
@darklow. Gotcha!

**Comment by RLJMedia** [comment]
Down the rabbit hole I go!

**Comment by RLJMedia** [comment]
I feel I have Ngnix setup correctly now.

The only problem now is I just noticed that the run collectstatic did not copy the files. 

0 static files copied, 116 unmodified.

So that is the issue right now.

**Comment by darklow** [comment]
No it is not an issue, it shows it already copied 166 files
0 files copied, because nothing has changed since you last time run collectstatic.
Check your nginx error log.
Also I see you have 500 error now.

Just curious, have you ever worked with Django before?
All these problems have nothing to do with `django-suit` but to related Django deployment.
Why don't you run with manage.py runserver at first, to see if it works at all.

**Comment by RLJMedia** [comment]
I am new to Django development. At this point this really a configuration issue. I will check the logs.

Thank you for helping.

**Comment by gamesbook** [comment]
@darklow is right - you really need to use 'runserver' while doing
development & testing.  Getting ready for production is a necessary step -
but you need to check that everything else is working first.  The Django
mailing list can help with deployment issues such as yours.

**Comment by RLJMedia** [comment]
Thank you!!!
