### ISSUE TITLE
ModelAdmin and has_add_permission set to False

### ISSUE THREAD

**Issue by gwaramadze** [darklow/django-suit#51]
If a model has has_add_permission method set to False...

```
class MyModelAdmin(admin.ModelAdmin):
    def has_add_permission(self, request):
        return False
```

...making "+Add" not displaying, the table for this model shrinks and becomes uneven in regard to other models. I don't know how to describe it better so I'll just attach an image.
![tcFQXNd](https://f.cloud.github.com/assets/1044831/290977/9ee9f10c-92f8-11e2-89cc-ee22c36534ec.png)

**Comment by muratenes** [comment]
thank you
