### ISSUE TITLE
Show all button not showing

### ISSUE THREAD

**Issue by Pawamoy** [darklow/django-suit#510]
I am not sure if it comes from Suit or Django itself, but I found on one page of my admin site that the "Show all" button/link is not showing, at the right of the pagination buttons.

Adding the parameter by hand in the request url (`?all=`) does not work either.
My admin class for the model uses custom columns (but other admins with custom columns have the "show all" button so it might not be the problem).

It also uses custom list filters, maybe the issue comes from that?

**Comment by darklow** [comment]
What Django and Django Suit versions are you using?
"Show all" is shown only if you are using search and results are more than one page:

Shown:
http://djangosuit.com/admin/examples/country/?q=island

Not shown:
http://djangosuit.com/admin/examples/country/?q=islands

**Comment by Pawamoy** [comment]
I am talking about the button in the pagination section, not always related to search queries.

![capture du 2016-06-13 15-56-52](https://cloud.githubusercontent.com/assets/3999221/16010007/90fb5a8a-317f-11e6-95bf-598ccff741b7.png)

What is weird is that I just restarted the server and now it is showing :sun_with_face: 

On the demo page you linked, the button is in fact not shown:

![capture du 2016-06-13 16-02-54](https://cloud.githubusercontent.com/assets/3999221/16010178/50f60f42-3180-11e6-92e1-c84a9e7244ec.png)


So if we want to show all results we must:

1. Have enabled a search bar?
2. And have searched for something then clicked "Show all"?

Why not always showing this button when using pagination and there are more than one page?

**Comment by darklow** [comment]
How would I know?! :)
This is Django related, not Django Suit:
https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/pagination.html#L10

**Comment by Pawamoy** [comment]
Oh yes indeed :smile: 

Even with something like
```html+django
{% if pagination_required or show_all_url %}&nbsp;&nbsp;<a href="{{ show_all_url }}" class="showall">{% trans 'Show all' %}</a>{% endif %}
```
?

**Comment by Shruti-kmt18** [comment]
I have added the search bar, still showing all is not showing in my screen
