### ISSUE TITLE
django-import-export buttons not correctly styled

### ISSUE THREAD

**Issue by attieretief** [darklow/django-suit#517]
Django version: 1.9.7
Django Suit version: 0.2.19
Python version: 2.7.10

Issue:
I am using django-import-export in django-suit
I have my app deployed to heroku
When I run "heroku local" I have no issues
But when I view my admin pages on heroku, import-export are not appearing as buttons, but rather is list items

Here is the resulting page source running locally

`<div id="content-main">
    <div class="inner-center-column">
      <div class="module filtered" id="changelist">
        <div class="toolbar-content clearfix">
            <div class="object-tools">
  <a class="btn" href="import/" class="import_link">Import</a>
  <a class="btn" href="export/?" class="export_link">Export</a> 
`

Here is the resulting page source running on heroku

`<div id="content-main">
    <div class="inner-center-column">
      <div class="module filtered" id="changelist">
        <div class="toolbar-content clearfix">
  <ul class="object-tools">
  <li><a href="import/" class="import_link">Import</a></li>
  <li><a href="export/?" class="export_link">Export</a></li>
`

**Comment by SalahAdDin** [comment]
@attieretief Put and image please.

**Comment by PaleNeutron** [comment]
I got the same problem and fix it by but reorder `INSTALLED_APPS`

```
INSTALLED_APPS = [
    'my_app',
    'suit',
    'import_export',
    ...
]
```
`import_export` should after `suit`
