### ISSUE TITLE
django-suit is incompatible with django-daterange-filter

### ISSUE THREAD

**Issue by kouroshparsa** [darklow/django-suit#523]
If this is a bug please specify versions you're using first.

Django version: 1.8
Django Suit version: 0.2.13
Python version: 2.7

Issue:
Django suit is incompatible with django-daterange-filter plugin.
The daterange-filter is very popular and useful so this is a very important bug to fix.
I've tried changing line 118 of
suit/templatetags/suit_list.py
and added
```
        if 'query_string' not in choice:
            continue
```
It avoids the admin page from breaking fatally but still the range filter does not operate.

**Comment by madthew** [comment]
did you manage to solve?

**Comment by darklow** [comment]
I'm afraid no new 3rd party app support will be introduced in Django Suit 0.2.x series as it is getting harder and harder to maintain all the many combinations of versions.
Very soon 0.2.x will be discontinued in favour of new upcoming brand new v2.0 which has much better 3rd party app support out of the box, read more here: #475 
You can try using it already.

**Comment by kouroshparsa** [comment]
Hi @darklow 
Sorry for the late reply. I did not get any emails...
I tried the new release and the date range filter works!
thanks a lot

**Comment by kouroshparsa** [comment]
@darklow my main problem with suit version 2 is that the left panel menu no longer shows up.
I don't care whether it is a menu on the top or on the left; I just want a menu as the official release.
Can you please guide me?
It's urgent for my company.
```
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP

TEMPLATE_CONTEXT_PROCESSORS = TCP + (
    'django.core.context_processors.request',
)

SUIT_CONFIG = {
    'ADMIN_NAME': 'My Company',
    'MENU': (
        'sites',
        {'label': 'Users', 'url': 'auth.user', 'icon':'icon-user'},
        {'label': 'Overview', 'icon':'icon-wrench', 'url': '/'},
    )
}
```

**Comment by darklow** [comment]
@kouroshparsa What is your version of Django?
For v2 you need to use `apps.py` config instead of `SUIT_CONFIG`:
See demo app:
https://github.com/darklow/django-suit/blob/v2/demo/demo/apps.py

**Comment by kouroshparsa** [comment]
@darklow I'm using django-suit==2.0a1.
Thanks for the help. I understand now. It's working.

**Comment by kouroshparsa** [comment]
@darklow unfortunately switching to v2 has broken several things on my app so I'm hesitant to use it:
- jquery used  to be accessible at the beginning of page load so I could use $("something") in the header script but now it seems to get loaded after the header. I've also tried putting
```
<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
```
in `site-packages/suit/templates/suit/admin/base.html` but it did not solve the issue.
- when I inherit from either
```
{% extends "admin/base_site.html" %}
```
or
```
{% extends "suit/admin/base.html" %}
```
I do not get the name of the logged in person along with the log out link on the top right which was very handy.

**Comment by kouroshparsa** [comment]
@darklow Good news. I discovered that the fix I suggested above actually works. For some reason I thought it was not working.
just adding
```
        if 'query_string' not in choice:
            continue
```
to
line 118 of suit/templatetags/suit_list.py
I suggest you go ahead and push this fix for the production release.

**Comment by joepreludian** [comment]
@kouroshparsa Hi there. Do You if has a PR fixing this? Thank You.
