### ISSUE TITLE
use USE_THOUSAND_SEPARATOR in django-suit

### ISSUE THREAD

**Issue by forance** [darklow/django-suit#529]
If this is a bug please specify versions you're using first.

Django version: 1.9
Django Suit version:0.2.18 
Python version: 2.7

Issue:

I am trying to enable thousand separator by setting below , which stated in https://docs.djangoproject.com/en/1.10/topics/i18n/formatting/

USE_L10N = True 
USE_THOUSAND_SEPARATOR = True
 
somehow nothing happen, neither in the list view nor form view. I wonder is this feature supported by django-suit? Or suit has another way to enable it.

Thanks
Any comments are appreciated.

Nick

**Comment by darklow** [comment]
Does it work if you remove `suit` from `INSTALLED_APPS`?
I really doubt it can be related to Django Suit app.

**Comment by forance** [comment]
darklow,

you are right. It's nothing to do with suit. came to the wrong place.
I will remove this post later..
Thanks

Nick
