### ISSUE TITLE
Working with Django Edge

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#545]
Django version: 1.10.1
Django Suit version: 0.2.21
Python version: 2.7.6

**Issue:**

I'd like to be able to use Django Suit after creating a project with Django Edge - https://github.com/arocks/edge .  However, after following the basic Suit install and configuration, the look-and-feel has not changed.

The only issue I can see is that this step in the install gave an error

```
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
```

```
ImportError: cannot import name TEMPLATE_CONTEXT_PROCESSORS
```

Is this because of the Django version I am using?

**Comment by darklow** [comment]
For Django 1.9 + There is no more TEMPLATE_CONTEXT_PROCESSORS setting.
I updated docs: http://django-suit.readthedocs.io/en/develop/getting_started.html#installation Point Nr 3

**Comment by gamesbook** [comment]
Thanks!
