### ISSUE TITLE
suit.js:199 Uncaught ReferenceError: Suit is not defined

### ISSUE THREAD

**Issue by keyvanm** [darklow/django-suit#546]
If this is a bug please specify versions you're using first.

Django version: django==1.10.2
Django Suit version: v2
Python version: 3.5.2

Issue: I did the standard installation procedure and when I loaded the admin the page wasn't styled. I then opened the inspector and saw this JS error.

**Comment by darklow** [comment]
Sorry, cannot replicate. 
Something must be wrong with your static files serving.

**Comment by noelpuru** [comment]
I am getting the same error. I installed my requirements.txt file which contains:

```
Django==2.2.*
-e git://github.com/darklow/django-suit.git@v2#egg=django-suit
```
And copied apps.py from here:
`https://github.com/darklow/django-suit/blob/v2/demo/demo/apps.py`
