### ISSUE TITLE
Question: Is it possible to generate a menu child from models/database ?

### ISSUE THREAD

**Issue by pedrorafaeln** [darklow/django-suit#548]
Django version: 1.10.2
Django Suit version: 0.2.21
Python version: 3.4.3

Hi, Is it possible to create a menu child from a query in the database(Models)?
If it is, how do I go about doing that ?

Thanks.

**Comment by darklow** [comment]
One way is you can override `menu.html` and add your own logic, template filters or tags, read it from another source, etc.

**Comment by pedrorafaeln** [comment]
Do you have any examples? Because I did try to edit menu.html, but got nowhere

**Comment by darklow** [comment]
You must put changed `menu.html` in `templates/suit` folder of your app which is before `suit` in `INSTALLED_APPS` settings. And then change the code according to what you want to have. Create new template tag which retrieves menu from database or just replace one branch etc.

**Comment by pedrorafaeln** [comment]
I was able to find and edit menu.html, but got nowhere with the code, that's what I meant, sorry.

How do I create a new/edit a template tag ?

**Comment by darklow** [comment]
https://docs.djangoproject.com/en/1.10/howto/custom-template-tags/

**Comment by pedrorafaeln** [comment]
Thanks a lot for the quick answers man, Suit is awesome.

**Comment by darklow** [comment]
@pedrorafaeln Thanks, glad you like it.
If you're just starting, make sure you try out new v2-dev.

**Comment by roddyofchina** [comment]
I also encountered this problem

**Comment by darklow** [comment]
I will think of few ways how to make it easier for upcoming v2-dev, however in version 1.x extending menu.html is the right way to do that.

**Comment by Bartvds** [comment]
Some nice and clean facilities to add custom elements in main menu, changelist and changeform would be very welcome. 

Overriding templates creates a maintenance burden but we always have to do this at some point to get that extra mileage from the admin. Django allows us to add extra urls to admins easily but putting the links and buttons in usable places is a hassle.

Also some facility to put stuff on index page would be nice. We've used `django-admin-tools` to get some panels and menus up quickly but is opinionated and has an ugly visual style.
