### ISSUE TITLE
"Add new inline" toolbar not being shown for SortableStackedInlines on v0.2.21

### ISSUE THREAD

**Issue by sunnychaudhari** [darklow/django-suit#551]
**Django version: 1.10.2
Django Suit version: 0.2.21
Python version: 2.7**

**Issue:**
I'm using django suit version 0.2.21 for my django admin app
Using django version 1.10.2
I'm facing issues with inlining model. I have two models customer and address as bellow.

![img2](https://cloud.githubusercontent.com/assets/3327368/20004355/ea41b64a-a2b1-11e6-9a22-634579a9dd39.png)
you can see here for address inline, **+ Add Address** label is disappeared. But when I run my django admin app without django suit that "+ Add Address" label is visible to add more addresses for same customer. 
here is my admin class
```
from django.contrib import admin
from django.contrib.admin import ModelAdmin
from .models import Customer, Address
from suit.admin import SortableStackedInline

class AddressInline(SortableStackedInline):
    model = Address
    fields = ['country','state','city']
    extra = 1
    sortable = 'order'

class CustomerAdmin(admin.ModelAdmin):
    model = Customer
    fields = ['first_name','last_name', 'email', 'phone']
    list_display = ('first_name','last_name', 'email', 'group', 'phone')
    list_per_page = 50
    inlines = [AddressInline]
admin.site.register(Customer, CustomerAdmin)

```

Can you please help me with the same , what should I do to make that label enable for my inline while using django suit.

**Comment by darklow** [comment]
Please post python code for your admin class and inline class.

**Comment by darklow** [comment]
Just recreated your setup on brand new Django 1.10.3 and Django Suit 0.2.21.
Works great for me.
Please check if your developer console shows any JavaScript errors or not found files.
![image](https://cloud.githubusercontent.com/assets/445304/20004849/4a0febe8-a297-11e6-9ce1-62fce29b838f.png)

**Comment by sunnychaudhari** [comment]
Cool let me try this once. May be I think I was using grappelli admin previously may be some js files creating some issues.

**Comment by darklow** [comment]
"Add another address" bar is added by Django admin (not Django Suit) javascript functions. 
I am betting there is JavaScript issue or error why it haven't been added, therefore first thing you should do is check Console for JS errors.

**Comment by sunnychaudhari** [comment]
For same configuration and same code I'm getting these console errors

![img3](https://cloud.githubusercontent.com/assets/3327368/20017607/5ced41a4-a2ea-11e6-90ad-8d255bc25ba0.png)

You are correct these are some javascript errors, but I have also created new setpup with **same versions as you mentioned above**, and here its showing these JS errors. Can you tell me how do I resolve this.

**Comment by darklow** [comment]
Something is really wrong with serving of static files. I think it might be because of grappelli, `grp` is related to it. Try installing fresh project or make sure you removed all part of grappelli.

**Comment by darklow** [comment]
Or if you're were using `collectstatic` make sure you delete all files and re-run it again.

**Comment by sunnychaudhari** [comment]
I did the same thing again in separate virtual environment but showing the same js erros. Infact removed grappelli completly. I have created simple django app inside separate virtualenv just with django 1.10.3 and still its showing the same js error. I don't think now its related with grappelli any more. It might be something different.

**Comment by darklow** [comment]
Try using regular stacked inlines instead of Sortable and see if anything changes.

**Comment by sunnychaudhari** [comment]
Ohh finally ... Got the issue. My browser have cached those js files, when I cleared the browser cache all those js errors have gone and **Add Address**  label shows up in Address inlining, so I have installed django suit and tested the same and yeah ...its now working with django suit as well. Thanks for your help.
