### ISSUE TITLE
Only page zero shows records

### ISSUE THREAD

**Issue by JerryWorkman** [darklow/django-suit#556]
If this is a bug please specify versions you're using first.

Django version: 1.8
Django Suit version: 0.2.22
Python version: 2.7.12

Issue:
Only page zero shows records
show_all and other pages do not list records
same result in Windows and Linux (Ubuntu)
settings.py:
SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'NordCAD Part Editor',
    # 'HEADER_DATE_FORMAT': 'l, j. F Y',
    'HEADER_TIME_FORMAT': 'f:i A',

    # forms
    # 'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    # 'SEARCH_URL': '/admin/auth/user/',
    # 'MENU_ICONS': {
    #    'sites': 'icon-leaf',
    #    'auth': 'icon-lock',
    # },
    # 'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        'sites',
    #    {'app': 'auth', 'icon':'icon-lock', 'models': ('user', 'group')},
    #    {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
    #    {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
        {'label': 'Part Viewer', 'icon':'icon-question-sign', 'url': '/parts/'},
    ),

    # misc
    'LIST_PER_PAGE': 15
}

**Comment by darklow** [comment]
I don't understand your issue.
Please post a screenshot with the problem.
Thanks

**Comment by JerryWorkman** [comment]
Note that Page 2 or 3 is selected and no records are shown. In addition if I click "Show All" only the first 15 records are shown. I get the same result on Windows manage.py runserver and Ubuntu Apache2 WSGI.

![screenshot 2016-12-01 10 19 27](https://cloud.githubusercontent.com/assets/1776448/20799331/cfb08bae-b7af-11e6-8f85-4085cb0e18f3.png)

**Comment by darklow** [comment]
Really weird. Please post your ModelAdmin class.

**Comment by JerryWorkman** [comment]
```
class CatalogAdmin( admin.ModelAdmin ):
    list_display = ('product_code', 'category', 'description',
                    'base_desc', 'fields')
    list_filter = ('category',)
    ordering = ('category', 'product_code',)
    search_fields = ('product_code', 'description', 'base_desc')
    readonly_fields = ('image_tag',)
    fieldsets = (
        (None, {'fields': (
            'image_tag', 'product_code', 'category',
            'description', 'base_desc', 'fields')
        }),
    )
    formfield_overrides = {
        models.CharField: {'widget': TextInput( attrs={'size': '20'} )},
        models.TextField: {'widget': Textarea( attrs={'rows': 4, 'cols': 20} )},
    }

admin.site.register (Catalog, CatalogAdmin)
```

**Comment by darklow** [comment]
Please temporary uncomment `suit` and see if you experience same bug and this is really Django Suit fault.

**Comment by JerryWorkman** [comment]
I commented out suit and the problem persisted.

I installed django-debug-toolbar to see the sql queries and found that I had a foreign key pointing to a field that was not the primary key. Problem solved.

Many thanks.
