### ISSUE TITLE
Newlines in custom read-only field templates being converted to html linebreaks

### ISSUE THREAD

**Issue by eltimsy** [darklow/django-suit#557]
Django version: 1.8.15
Django Suit version: 0.2.18
Python version: 2.7.3

Issue: 
The fieldset.html template is adding linebreaks for every newline in our custom read-only field template. 

![linebreaks issue](https://cloud.githubusercontent.com/assets/20710659/20799367/f1d64f5c-b7af-11e6-859a-43fc42ddf30d.png)

Problem is coming from admin/includes/fieldset.html template.  The linebreaksbr filter is causing it.

![screen shot 2016-12-01 at 10 23 04 am](https://cloud.githubusercontent.com/assets/20710659/20799820/5f0237d4-b7b1-11e6-9e74-647dc1e1006c.png)

**Comment by darklow** [comment]
Related to #351 
Django fixed it differently, undoing this PR.
https://github.com/django/django/commit/d345a030c2f3b332512e5091248dd8b06e859eac
