### ISSUE TITLE
JS Syntax error with jQuery 2.2.4 & Suit tabs

### ISSUE THREAD

**Issue by philoozushi** [darklow/django-suit#558]
Django: 1.9
Django Suit: 0.2.22 (jQuery: 2.2.4)
Python: 2.7

Using Suit tabs, and opening a suit page directly on a selected tab,
e.g. http://mydomain.com/admin/myapp/mymodel/1234/change/#my-tab

We have the following JS error :
```
Error: Syntax error, unrecognized expression: a[href=#my-tab]
```
Because this jQuery version needs quotes in this case.
`a[href="#my-tab"]` will work.

I'll try to submit a pull request.

**Comment by darklow** [comment]
Hi, I think it was fixed already in #554 
Could you try develop version and see if it fixes.
I will release new versions afterwards.

**Comment by darklow** [comment]
```
pip install django-suit==0.2.23
```

**Comment by philoozushi** [comment]
Great, thanks 😉
