### ISSUE TITLE
New project, shall use current version or V2?  Feature breakdown?

### ISSUE THREAD

**Issue by gbcgit** [darklow/django-suit#559]
Hello,

Django Suit looks great.   I'm ready to commit to using it.   And I'm happy to pay for it.   Just need to determine which version to use.  

This is an intranet, and I'll be highly customizing the Admin.   Is there a feature breakdown between the two?   

Thank you
Genes

**Comment by darklow** [comment]
I advise using v2 (just some are missing, see #475). Using it by myself in many projects already. It will have almost same features and it is based on new Bootstrap v4-alpha with all the benefits, while current version is using outdated Bootstrap 2 and also current version won't receive any new features in future.

**Comment by gbcgit** [comment]
Hi Kaspars,

You don't happen to have a V2 demo like the current version one do you?
If not, I'll fetch it, and try it.   But, the statements I've seen
regarding there being no documentation for V2, I'm concerned I won't know
it's capabilities.   For example, one use case I'm hoping to find with Suit
or some other 3rd party, is a from/to date widget to filter django admin
changelists.

Thanks
Gene

**Comment by gbcgit** [comment]
Hey, nevermind, I found the demo on #475.   Thanks !!!!

Gene

**Comment by darklow** [comment]
Yes, demo and even .sqllite file with test data is now included in v2:
https://github.com/darklow/django-suit/tree/v2/demo
