### ISSUE TITLE
[TypeError] __str__ returned non-string (type bytes)

### ISSUE THREAD

**Issue by GitBib** [darklow/django-suit#570]
If this is a bug please specify versions you're using first.

Django version:  1.9.6
Django Suit version: 0.2.24
Python version:  3.5.2

Issue: The problem comes from the fact that there are no posts. "__str__ returned non-string (type bytes)"
\suit\templates\admin\change_list.html, error at line 102: "{% result_list_with_context cl %}"
```
`92	            {% if cl.formset.is_multipart %}
93	              enctype="multipart/form-data"{% endif %} class="form-inline" novalidate>{% csrf_token %}
94	          {% if cl.formset %}
95	            <div>{{ cl.formset.management_form }}</div>
96	          {% endif %}
97	
98	          {% block result_list %}
99	            {% if cl.result_count %}
100	              {% if action_form and actions_on_top and cl.full_result_count %}
101	                {% admin_actions %}{% endif %}
102	              {% result_list_with_context cl %}
103	
104	              {% if action_form and actions_on_bottom and cl.full_result_count %}
105	                {% admin_actions %}{% endif %}
106	            {% else %}
107	              {% suit_bc_value 1.5 'pop' 1.6 '_popup' as POPUP_VAR %}
108	              <div class="alert alert-block alert-info">
109	                {% if cl.full_result_count %}
110	                  <h4>{% trans 'Nothing found' %}!</h4>
111	                  <br>
112	                  <a href="?{% if cl.is_popup %}{{ POPUP_VAR }}=1{% endif %}">{% trans 'Reset search and filters' %}</a>`
```

**Comment by darklow** [comment]
Please provide full traceback (use pastie)

**Comment by GitBib** [comment]
![screencapture-file-c-users-banek-desktop-typeerror-20at-20_admin_metodrazrab_eventlecturer_-html-1485978233434](https://cloud.githubusercontent.com/assets/15717621/22523305/f68426b8-e8cf-11e6-8843-3ac5ef87bb6a.png)

**Comment by darklow** [comment]
1) Could you tell me how to replicate this error? For empty list I got no such error.
2) Does error disappears if you remove `suit` from `INSTALLED_APPS`?
