### ISSUE TITLE
Release schedule for next version

### ISSUE THREAD

**Issue by beruic** [darklow/django-suit#571]
I'm working on a project that will definitely generate revenues for django-suit in the future. We are still in the early stages of developing our new admin panel, but I have noticed that PyPI has a version `0.3a3` available. Therefore we would like to know how soon we can expect a stable version of the next release, so we can decide whether to start using it already now.

**Comment by darklow** [comment]
0.3a3 is deprecated and was based on Bootstrap 3. I highly suggest you using v2-dev based on Bootstrap v4 alpha. More here: https://github.com/darklow/django-suit/issues/475
