### ISSUE TITLE
The django suit version v2 whether support the django filer.

### ISSUE THREAD

**Issue by fastdevops** [darklow/django-suit#576]
If this is a bug please specify versions you're using first.

Django version: 1.9.12
Django Suit version: v2
Python version: 3.5

Issue:

**Comment by burakk** [comment]
Hi, 
Django filer page display is broken in admin  with the below configuration.
[django==1.11.1]
django-filer==1.2.7
django-suit==2.0a1
python3.6.1

**Comment by ebertti** [comment]
I make a smallfix to reduce the "broken"

Create in you template folder on this path:

`{{template_path}}/admin/filer/folder/directory_listing.html`

With this content:

```html
{% extends "admin/filer/folder/directory_listing.html" %}
{% load suit_tags %}

{% block bodyclass %}{{ block.super|suit_body_class:request }} change-list filebrowser{% endblock %}
```

Now has a little css broken, but you can use.

**Comment by FabriceSalvaire** [comment]
Edit icon `<span class="edit-file"><span class="fa fa-pencil"></span></span>` is moved to the right and hidden due to this rule

```
 .control-group .related-lookup {
  text-indent: 200%;
}
```
