### ISSUE TITLE
v2: horizontal filters max-width & better horizontal filter title lables

### ISSUE THREAD

**Issue by 77cc33** [darklow/django-suit#584]
If this is a bug please specify versions you're using first.

Django version: 1.10.5
Django Suit version: 2.0a1
Python version: 2.7.12

Issue: Some time "max-width: 200px" is not enough to include all filter information as after filter applied, it also adds title of filter as select list value:

![image](https://cloud.githubusercontent.com/assets/2612157/23728690/dddc043e-0466-11e7-9e55-f03e2e4ee2f9.png)

Here are 2 suggestions:
1. Maybe you can add **suit_list_filter_horizontal_max_width** option, to easy override this value when needed?
2. Maybe it's good to implement this filter labeling as it's done on Shopify Shops:
![image](https://cloud.githubusercontent.com/assets/2612157/23728886/c4d9001c-0467-11e7-9a50-ceb3a84fc09e.png)

As you can see labels here goes on the TOP of select list value and doesn't eat horizontal space, here you can check it live and maybe grab styles: https://checkout.shopify.com/17723005/checkouts/b85fdcfe88679471cdf3d1eaad59b7f3

**Comment by darklow** [comment]
1. You can override this with your own CSS, I don't think involving python into defining select width is good idea. There inline style right now, but I just forgot to move it into global css.
2. That is a major feature and would require overriding lot's of templates, not sure it can work with Django Admin.
