### ISSUE TITLE
Missing Datepicker

### ISSUE THREAD

**Issue by caliph007** [darklow/django-suit#586]
I am missing any kind of datepicker for my models.DateField in admin.

![capture](https://cloud.githubusercontent.com/assets/743333/24210655/1099a16a-0f2a-11e7-8413-f884c21a67a7.JPG)

Django 1.10.5
Suit 0.2.24

No JS Errors in the browser console. 
Shouldn't the datepicker appear by default?

**Comment by darklow** [comment]
Fix available in newest version:
`pip install django-suit==0.2.25`
