### ISSUE TITLE
Navigation menu error on edit or create model [v2]

### ISSUE THREAD

**Issue by ebertti** [darklow/django-suit#587]
If this is a bug please specify versions you're using first.

Django version: 1.10.5
Django Suit version: v2 from git
Python version: 3.5

Issue:

Error on navigation MENU on create, edit model

![navigation_error](https://cloud.githubusercontent.com/assets/140394/24251335/9b182be8-0fb8-11e7-9f50-de751d8edb36.gif)

**Comment by darklow** [comment]
Please post your full config of Django Suit.

**Comment by ebertti** [comment]
```python
class SuitConfig(DjangoSuitConfig):
    layout = 'horizontal'
    list_per_page = 50

    menu = (
        ParentItem(app='clientes', icon='fa fa-user'),
        ParentItem(app='emprestimos', icon='fa fa-briefcase'),
        ParentItem(app='pagamentos', icon='fa fa-magnet'),
        ParentItem(app='legacy', icon='fa fa-exclamation'),
        ParentItem('Relatórios', icon='fa fa-file', url=reverse_lazy('explorer_index')),
        ParentItem('Usuários', children=[
            ChildItem(model='auth.user'),
            ChildItem('User groups', 'auth.group'),
        ], align_right=True, icon='fa fa-lock'),
        ParentItem(app='dominio', align_right=True, icon='icon-globe'),
    )
```

**Comment by darklow** [comment]
Please post also URL addresses of both pages: list page where you click Add new item and resulting URL where menu is not activated.

**Comment by ebertti** [comment]
Click ADD

`http://localhost:8000/admin/pagamentos/cobranca/`
`http://localhost:8000/admin/pagamentos/cobranca/add/`

Default navigation active on add or edit page

`http://localhost:8000/admin/clientes/`

The navigation and linking is OK. The problem is the active menu page.

**Comment by ebertti** [comment]
https://github.com/darklow/django-suit/pull/590

**Comment by ebertti** [comment]
#590 Take a look on this PR

**Comment by darklow** [comment]
Accepted your PR. Thanks.

**Comment by ebertti** [comment]
Thanks!
