### ISSUE TITLE
Extend kitchen soup example: color

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#591]
Please can you add an example showing  use of an HTML5 color input in the form example for `http://djangosuit.com/admin/examples/kitchensink/`

W3Schools examples:

* https://www.w3schools.com/html/html_form_input_types.asp
* https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_color

I am assuming the color code will/should be stored as plain text?  Not sure how this would look in the admin list (perhaps a custom model def incorporating an HTML tag?).

**Comment by darklow** [comment]
@gamesbook I updated demo with some html5 widgets. For color widget all you need to do is extend `TextInput` and use it as a widget:
```py
from django.forms import TextInput

class ColorInput(TextInput):
    input_type = 'color'
```
Demo: http://localhost:8002/admin/demo/showcase/1/change/
Code: https://github.com/darklow/django-suit/blob/v2/demo/demo/admin.py#L228

![image](https://cloud.githubusercontent.com/assets/445304/24793523/094daa7e-1b8b-11e7-9343-3c5aa6e17ddd.png)

**Comment by gamesbook** [comment]
Thanks!
