### ISSUE TITLE
Version 2 doesn't show horizontal SimpleListFilter 

### ISSUE THREAD

**Issue by yveswehrli** [darklow/django-suit#592]
If this is a bug please specify versions you're using first.

Django version: 1.9.12
Django Suit version: v2(1dd776b6bbf3b47e8c1497c772d88943b5c4677d)
Python version: 3.6.0

Issue: 
In my project I have some filters based on the django SimpleListFilter class. If I add them to 'suit_list_filter_horizontal', they still show up on the right side. Is it even possible to add them to the horizontal filters?

**Comment by darklow** [comment]
It is possible, use `parameter_name` for `suit_list_filter_horizontal`, but if I just noticed if you don't have `search_fields` you may not see whole search form. Try adding `search_fields` too. I will need to make a fix for this.

**Comment by yveswehrli** [comment]
Hey darklow, thx for you're answer. I have search_fields, so the form is visible. I didn't quite got what you mean with parameter_name. Do you have an example?

**Comment by darklow** [comment]
Please post a code of your filter and how do you include it to `list_filters`.

**Comment by yveswehrli** [comment]
Filter:
```
class MerchantListBaseFilter(admin.SimpleListFilter):
    title = 'Merchant'
    parameter_name = 'merchant'

    def get_lookup(self, node):
        id = node.id
        name = "%s - %s" % (node.merchant.name, node.merchant_identifier)

        return id, name

    def lookups(self, request, model_admin):
        lookups = []
        for merchant in MerchantId.objects.all().prefetch_related('merchant'):
            lookups.append(self.get_lookup(merchant))
        return lookups

    def queryset(self, request, queryset):
        if self.value():
            filtr = {
                self.key: self.value()
            }
            return queryset.filter(**filtr)
        return queryset
```

In admin:
```
    list_filter = [
        MerchantListFilter,
    ]

    suit_list_filter_horizontal = [
        MerchantListFilter
    ]
```

**Comment by darklow** [comment]
You don't use class, you need to use it by parameter or field name as you can use same class in filters multiple time by different parameter_name:
Use: 
`suit_list_filter_horizontal = ['merchant']`

**Comment by yveswehrli** [comment]
Thank you very much for you're fast and good answer!
It's working very well :D
