### ISSUE TITLE
Update required in copyright.

### ISSUE THREAD

**Issue by sravi4701** [darklow/django-suit#596]
If this is a bug please specify versions you're using first.

Django version: 
Django Suit version: 
Python version: 

Issue: In the website the copyright year is 2013. I think it should be 2017.

**Comment by darklow** [comment]
O wow, thanks, haven't looked at footer of website for a while. :)

**Comment by sravi4701** [comment]
Can I work on this ?

**Comment by darklow** [comment]
What do you mean?

**Comment by sravi4701** [comment]
Can I fix this ?

**Comment by darklow** [comment]
Thanks for the offer, but website is not the part of django suit repository. Just deployed a fix.

**Comment by sravi4701** [comment]
Okay
