### ISSUE TITLE
Menu does not highlight correct button for custom URL ParentItem

### ISSUE THREAD

**Issue by Bartvds** [darklow/django-suit#602]
Django version: 1.10.6
Django Suit version: /tarball/94b54c678848a8713989bce4378238b4d87cadf6 (hour ago)
Python version: 3.5.1

Issue:

When I put a ParentItem with a custom url (name) in the menu and then click on it I get the correct page, with admin menu, but it highlights the first regular ParentItem (but not a sub app).

Config (stripped down to essentials while still showing error):

````
class SuitConfig(DjangoSuitConfig):
    verbose_name = 'My App'

    menu = (
        ParentItem('Users', children=[
            ChildItem(model='users.user'),
            ChildItem(model='auth.group'),
        ], icon='fa fa-cog'),
        ParentItem('Exports', url='export-index'),
    )
````

So in this example I would get the page `export-index` but the menu highlights the `Users` item (but not a ChildItem). Like so:

![image](https://cloud.githubusercontent.com/assets/685984/25003890/d592fc04-2051-11e7-91f1-f796fe3cf7a2.png)

The view is using: `context = admin_site.each_context(request)` to get the admin template context setup and the `{% extends "admin/base_site.html" %}` and puts a dumb table in the `content` block.

**Comment by gamesbook** [comment]
Is this related to #601 ?

**Comment by darklow** [comment]
And seems identical to https://github.com/darklow/django-suit/issues/587 as well.
@Bartvds are you on latest develop version too?

**Comment by darklow** [comment]
I was able to reproduce, working on a fix now.

**Comment by Bartvds** [comment]
@gamesbook I saw your issue #601 in my github feed and remembered I needed to report this for a while.

**Comment by darklow** [comment]
Just one function call was missing :) Should be fixed now.
```
pip uninstall django-suit
pip install https://github.com/darklow/django-suit/tarball/v2
```

**Comment by gamesbook** [comment]
Works for me.

**Comment by Bartvds** [comment]
Oh wow you are fast 🚀

Works for me too. Thanks :)

**Comment by Bartvds** [comment]
Problem solved so I'll close :+1:
