### ISSUE TITLE
action field displays an error in the history list .

### ISSUE THREAD

**Issue by liron-li** [darklow/django-suit#604]
If this is a bug please specify versions you're using first.

Django version: 1.10
Django Suit version: 0.2.25 
Python version: 3.6

Issue:  action field displays an error in the history list . 

like this：
> 	[{"added": {}}]

**Comment by darklow** [comment]
Please submit more detailed report and description of the problem including full error stacktrace and example code that shows how to replicate error.

**Comment by kliyes** [comment]
@liron-li check #533

**Comment by liron-li** [comment]
![image](https://cloud.githubusercontent.com/assets/24496043/26487176/ed327e38-4230-11e7-80b6-782aa10ecbed.png)

l
