### ISSUE TITLE
Bootstrap 4 

### ISSUE THREAD

**Issue by burakk** [darklow/django-suit#620]
Django version: 1.11.1
Django Suit version:  django-suit==2.0a1
Python version: 3.6.1

Issue:  My admin with django-suit is not responsive. I have checked the head section of the html created and there is no viewport meta tag ( no bootstrap included ). Am I missing something?

Thank you...

**Comment by paulorsbrito** [comment]
It would be a nice plus. The lack of responsiveness is making me consider other admin template options.
