### ISSUE TITLE
Just add a custom url to admin menu?

### ISSUE THREAD

**Issue by realsby** [darklow/django-suit#621]
I want to add a custom url to django admin. Do I have to write all my apps in SUIT_CONFIG ? Is there any easy way to add just a custom link? Thanks 

`SUIT_CONFIG = {
    'ADMIN_NAME': 'Test Admin',
    'MENU': (
        'SOME_MAGIC',
        {'label': 'Translations', 'icon': 'icon-question-sign', 'url': '/translation/'},
    ),
}`

**Comment by darklow** [comment]
Only way is to define config, believe me, you will want to do that sooner or later anyway, to re-order by another logic (Configuration, Content, etc).
