### ISSUE TITLE
Admin messages not displaying after an action

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#626]
If this is a bug please specify versions you're using first.

Django version:  1.10.7
Django Suit version:  2.0a1
Python version:  3.5.3

Issue:

For the 'vertical' layout, the admin messages are not showing up after an action has been completed (they do so in 'horizontal' mode)

**Comment by darklow** [comment]
Should be fixed now:
```
pip uninstall django-suit
pip install https://github.com/darklow/django-suit/tarball/v2
```

**Comment by gamesbook** [comment]
Is there anyway to see what update of suit is running in a local install? i.e. is there a datestamp, for example, somewhere in a primary file?
