### ISSUE TITLE
Paging on inlines

### ISSUE THREAD

**Issue by skndn60** [darklow/django-suit#65]
Would it be possible to have a paging feature on inlines (tabular) like the paging one sees on basic change_list?

**Comment by assem-ch** [comment]
useful code

**Comment by cchacholiades** [comment]
Really useful code, how can this be implemented to support multiple TabularInlines?

**Comment by boddah-182** [comment]
great solution

**Comment by kittylon** [comment]
when I try to update anything in the form I get this response:

Column with this Schema and Sequence number already exists.
