### ISSUE TITLE
suit_list_filter_horizontal not filtering

### ISSUE THREAD

**Issue by cometsong** [darklow/django-suit#655]
Django version: 1.11.7
Django Suit version: 2.0a1 (latest commit # 613c84c)
Python version: 3.6.1

Issue:
I have in my admin.py: 
```
list_filter = ( 'project_code', 'sample_type', .... , )
suit_list_filter_horizontal = list_filter
```
but although the horizontal filter displays, it does no selection filtering, just returns the same page with the query_string: `?q=`.  When I comment out that line, the original vertical filter lists work successfully.

How can I troubleshoot this?  Do you know which methods you've overridden that I can add logging statements into? (I have the install from the cloned git repo.)

Thanks!

**Comment by cometsong** [comment]
Decided not to bother any more troubleshooting this.  Case closed.  :)

**Comment by gamesbook** [comment]
Is it working now?

**Comment by cometsong** [comment]
No it's still not working.
I'm going with a different technique.
