### ISSUE TITLE
No module named suit

### ISSUE THREAD

**Issue by Shawnmhy** [darklow/django-suit#667]
If this is a bug please specify versions you're using first.

Django version: 2.0.3
Django Suit version: 0.2.25
Python version: 3.6.4

Issue: 
Hi Everyone!
I installed the django-suit successfully, and I also added 'suit' in the INSTALLED_APPS before 'django.contrib.admin', however when I do 'python3 manage.py makemigrations' it appears that 'no module named suit', could somebody please help me?

Shawn

**Comment by gamesbook** [comment]
I don't think `suit` is an app. Have you tried removing it and rerunning the migrations?

**Comment by Shawnmhy** [comment]
If I delete 'suit' from settings.py, then I can run the server correctly, but the theme remains the original type.

**Comment by gamesbook** [comment]
Have a look at the example  in the demo app:
https://github.com/darklow/django-suit/blob/v2/demo/demo/settings.py

**Comment by theArjun** [comment]
First uninstall the `django-suit`.
```pip uninstall django-suit```

Then install from `v2`.
```pip install https://github.com/darklow/django-suit/tarball/v2```

**Comment by sharmila-polamuri** [comment]
I got same error. Please any one help to fix this problem.
