### ISSUE TITLE
V2 Release

### ISSUE THREAD

**Issue by jpic** [darklow/django-suit#669]
Is it possible to make a v2 rc release ?

Meanwhile, for people in need, i have published a django-jpic-suit pypi package for deployment of betagouv/mrs project, feel free to use ;)

**Comment by gamesbook** [comment]
While I agree a release would be good, why do we need to use this rather than : 
```
pip install https://github.com/darklow/django-suit/tarball/v2
```

**Comment by jpic** [comment]
Is it possible to add this to setup.py install_require ?

**Comment by darklow** [comment]
@jpic You shouldn't add commercial library to your MIT licensed project as dependency.
Read more about licensing: http://djangosuit.com/pricing/

**Comment by jpic** [comment]
We have already registered an OEM integrator license, do you think it can
cover the release ?

**Comment by jpic** [comment]
So, is this going to work ?
![2018-04-01-050650_753x765_scrot](https://user-images.githubusercontent.com/94636/38169461-bd06e36a-356a-11e8-979c-e002cb5076b0.png)

**Comment by jpic** [comment]
I thought our OEM license would cover for it, it's not a reusable project really, it's just open source for research.
Sorry for the mistake we have removed django-suit.

**Comment by shayneoneill** [comment]
Could you please reconsider not having a proper pip release. I cant for the life of me figure out how to work this weird install method into uv (uv pip install https://github.com/darklow/django-suit/tarball/v2  doesnt work at all)

**Comment by gamesbook** [comment]
This project is "on hold" and changes are happening in the forks; for example, we install from pulse-mind as follows:
```
uv pip install django-suit-v2-pm git+https://github.com/pulse-mind/django-suit.git@b40ed96a1ef912aae8878e693bd43dc1c8dbae52
```
