### ISSUE TITLE
Custom filters do not appear in horizontal row

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#679]
Django version: 1.11.12
Django Suit version: 2.0a1
Python version: 3.4.3

**Issue:**

In the admin, given that I have:

```
    list_filter = (filters.ActivityBySiteFilter, filters.SiteActivityListFilter,
                   'planned_date', 'completed_date', 'responsible',
                   'date_change', 'edited_by', 'actual_date',)
    suit_list_filter_horizontal = (
        filters.ActivityBySiteFilter, filters.SiteActivityListFilter,
        'planned_date', 'completed_date', 'responsible',
        'date_change', 'edited_by', 'actual_date',)
```
All the normal filters  ('name') appear across the top in a single row; but the two custom filters do not.  

Please can suit be updated to display these as expected?

**Comment by shulcsm** [comment]
`suit_list_filter_horizontal` is expecting string value of "filter_id" see here: https://github.com/darklow/django-suit/blob/v2/suit/templatetags/suit_list.py#L216
Current implementation is very naive but i don't see any obvious solutions since `ListFilter` doesn't implement string id.

P.S.: If you want to make all your filters horizontal you can do `suit_list_filter_horizontal = '__all__'`

**Comment by jayWarr** [comment]
I have the  identical problem to **gamesbook** with the similarbehaviour.
I tried the solution:
`suit_list_filter_horizontal = '__all__'`
 All my horizontal filters disappeared and were replaced by a vertical 1st-in-the-list filter ?!

**Comment by gamesbook** [comment]
@jayWarr "All my horizontal filters disappeared and were replaced by a vertical 1st-in-the-list filter"
Yes, I have the same outcome. 
`suit_list_filter_horizontal = '__all__'`
does not work.

**Comment by gamesbook** [comment]
I have uninstalled and re-installed and now the changes are through.

It would be ideal if the tag was updated though....

**Comment by darklow** [comment]
Hmm, why not use it like this:
```
list_filter = (filters.ActivityBySiteFilter, ...)
suit_list_filter_horizontal = list_filter

**Comment by gamesbook** [comment]
@darklow Its not always a 1:1 mix.  But I have since found you can refer to a SimpleListFilter by its parameter name.
