### ISSUE TITLE
Display user information in relational structure

### ISSUE THREAD

**Issue by Ishan3333** [darklow/django-suit#688]
Hi. First of all, a brilliant project you have developed there. I am using this project for an academic project. I have integrated it with an existing django project and it works just fine. When i work my way around displaying the user information, the information itself is displayed fully but it is displayed in a monotonous manner and not in arranged tabled way. I am posting a screenshot of how the info is displayed in my case.

![screenshot from 2018-05-22 11-23-55](https://user-images.githubusercontent.com/26248679/40344600-2442dbae-5db3-11e8-98bb-418f641a960e.png)

I want the same page to be displayed in the following way !

![screenshot from 2018-05-22 11-33-30](https://user-images.githubusercontent.com/26248679/40344776-f976b9c6-5db3-11e8-8700-16fa7815e0fe.png)

 If any one can please help me it would be really appreciated ! Thanks in advance.

**Comment by darklow** [comment]
@Ishan3333 You need to use fieldsets to group fields.
See demo: http://v2.djangosuit.com/admin/demo/country/169/change/
Code: https://github.com/darklow/django-suit/blob/v2/demo/demo/admin.py#L76

**Comment by Ishan3333** [comment]
Yes. How imbecile of me. Thanks for pointing out. Much appreciated !
