### ISSUE TITLE
The calendar button of the DateField cannot be show in SortableTabularInline.

### ISSUE THREAD

**Issue by fastdevops** [darklow/django-suit#689]
django suit v2
django v1.11.3

The SortableStackedInline can show the datefield with the calendar icon. But the SortableTabularInline cannot show the calendar button

![2018-05-28_154338](https://user-images.githubusercontent.com/15835056/40603269-0b7c4120-628e-11e8-8247-229dcda7ec2e.png)

**Comment by shulcsm** [comment]
I'm not sure but IIRC it's caused by missing class and solved by #623 can you confirm?

**Comment by fastdevops** [comment]
It works because the path of the static folder is not right, thanks!
