### ISSUE TITLE
Payment Category Cannot be selected

### ISSUE THREAD

**Issue by mmatisans** [darklow/django-suit#690]
>Add Event
>select building
>fill all forms
>will not apply "Payment category is not selected for building."
>go to Building profiles
>Edit Building
>Payment category is unable to be clicked or selected.
![capture](https://user-images.githubusercontent.com/40034088/41109209-6da533d0-6a44-11e8-8fa1-084f3f386339.JPG)

**Comment by darklow** [comment]
Please ask your developer for support.
