### ISSUE TITLE
Search through raw_id_field popup breaks functionality in v2

### ISSUE THREAD

**Issue by Bartvds** [darklow/django-suit#692]
If you open the raw_id_fields popup and then use the search in the popup the content reverts to a regular list view, so when you click an item you don't select it for the field but instead open the edit view inside the popup.

I'm using suit from the v2 branch.

It is like this issue but in the new skin: https://github.com/darklow/django-suit/issues/190

**Comment by YukSeungChan** [comment]
+1

**Comment by darklow** [comment]
Merged thanks.
