### ISSUE TITLE
RemovedInDjango30Warning: {% load admin_static %} is deprecated

### ISSUE THREAD

**Issue by amureki** [darklow/django-suit#710]
Greetings,

thank you for the great package!
We are using it in one of our projects (latest PyPI version) and recently we started getting some deprecation warnings in our logs:
```
RemovedInDjango30Warning: {% load admin_static %} is deprecated in favor of {% load static %}.
```
https://docs.djangoproject.com/en/2.1/releases/2.1/#id2

I did a small check and found out that `django-suit` is using this deprecated tag, we should consider refactoring this.
https://github.com/darklow/django-suit/search?q=admin_static&unscoped_q=admin_static

**Comment by henrythor** [comment]
Is this project dead, or does it not plan to support Django 3.0? One whole year and noone has commented on this or reviewed the patch?

**Comment by coredumperror** [comment]
This issue is still not fixed. In Django 3.0, suit's code crashes widgets.py line 6:

`ModuleNotFoundError: No module named 'django.contrib.admin.templatetags.admin_static'`

**Comment by darklow** [comment]
@coredumperror It is fixed, but this issue and mentioned PR was about v2 branch. Looks like it has to be fixed in v1 version (master/develop branches) too.
