### ISSUE TITLE
I'm adding a sponsor but then it's not found

### ISSUE THREAD

**Issue by kiote** [darklow/django-suit#717]
with a message `sponsor with ID "3078" doesn't exist. Perhaps it was deleted?`
or whichever ID was assigned to sponsor. Tried several times here: https://djangogirls.org/admin/sponsor/sponsor/add/

Although once I was able to add a sponsor, but can't repeat this success anymore :)

**Comment by darklow** [comment]
Please contact your developer, this is github for django-suit only.
