### ISSUE TITLE
The menu is not displayed with last version of chrome (Version 77.0.3865.75 (Build officiel) (64 bits))

### ISSUE THREAD

**Issue by pulse-mind** [darklow/django-suit#735]
The menu that should be displayed on left is not displayed since last version of Chrome : Version 77.0.3865.75 (Build officiel) (64 bits)

Same problem on the demo https://djangosuit.com/admin/

**Comment by Napoleon-Black** [comment]
I have the same issue on Chrome Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by daniel-clayton** [comment]
Looks like the menu is being positioned way of the edge of the screen for some reason

**Comment by pulse-mind** [comment]
By modifying the css (with inspect mode) I can display the menu at the bottom :(
```
#suit-left {
    width: 200px;
    right: 0px;
    margin-left: -11%;
}
```

**Comment by andremerlo** [comment]
Quick fix, by modifying the css (not tested on previous Chrome versions)

```css
#suit-left {
    width: 200px;
    left: 0px;
    position: absolute;
}
```

**Comment by yoelnacho** [comment]
Partial fix (chrome 76 and 77).

`.suit-columns.two-columns {
    position: relative;
    min-height: 500px; // replace it with minimum menu height
}
#suit-left {
    left: 0;
    position: absolute;
    margin-left: 0;
}
`

**Comment by minholi** [comment]
Can be fixed with this:

`
.suit-columns { display: flex; }`

**Comment by kingmray** [comment]
We have the same Problem with V1. Would you provide a patch for this version?

**Comment by gamesbook** [comment]
Likewise.  This is quite urgent as we have users that are already on v77.x of Chrome.

**Comment by pulse-mind** [comment]
You can add it by yourself in your project in the code as inline CSS. In my case I used the solution given before
`.suit-columns { display: flex; }`

**Comment by ayush--s** [comment]
just fixed by adding css suggested in https://github.com/darklow/django-suit/issues/735#issuecomment-531397105 to `templates/admin/base_site.html` (for v1 suit admin)

**Comment by gamesbook** [comment]
Will this fix appear "as is" in a code patch (for versions 1 and 2)?

**Comment by ahmedouvic** [comment]
Fixed it by adding 
```
{% block extrastyle %}
{{ block.super }}
<style>
    .suit-columns { display: flex; }
</style>
{% endblock %}
```
under *templates/admin/base_site.html*

**Comment by darklow** [comment]
Fixed in newest version. Thanks to all contributors.
```
django-suit==0.2.28
```
