### ISSUE TITLE
HRS: in new version of Chrome left menu is missing

### ISSUE THREAD

**Issue by sedvick** [darklow/django-suit#739]
After updating Chrome, left menu missing in HRS
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/51958277/66022483-d3eb1f00-e4f6-11e9-82cb-4e91098426fc.png)

**Comment by gamesbook** [comment]
This is a duplicate of #735

**Comment by darklow** [comment]
Fixed in newest version. Thanks to all contributors.
```
django-suit==0.2.28
```
