### ISSUE TITLE
Left hand nav in Django admin not shows in Chrome

### ISSUE THREAD

**Issue by davidkrcil** [darklow/django-suit#741]
Please does any body know why Left hand navigation does not show in Chrome?
Django Suit version 1, Django 1.8

**Comment by amureki** [comment]
Hey @davidkrcil !
This should be solved in the latest release (`django-suit==0.2.28`), see
https://github.com/darklow/django-suit/issues/719
https://github.com/darklow/django-suit/issues/735
https://github.com/darklow/django-suit/issues/739
