### ISSUE TITLE
a version django-suit is not valid

### ISSUE THREAD

**Issue by suzanneloures** [darklow/django-suit#745]
I am trying to put the project on the web server but when trying to install django by requirements.txt is informed that there is no version
django-suit==2.0a1

**Comment by gamesbook** [comment]
Its not released as a pip installable - see #699

To install: https://django-suit.readthedocs.io/en/v2/install.html

**Comment by dawit-nigusu** [comment]
> I am trying to put the project on the web server but when trying to install django by requirements.txt is informed that there is no version
> django-suit==2.0a1

did you get a solution for this ,let me know if you do please

**Comment by suzanneloures** [comment]
a gamesbook solution worked!
To install: https://django-suit.readthedocs.io/en/v2/install.html

**Comment by darklow** [comment]
```
# requirements.txt
 -e git://github.com/darklow/django-suit.git@v2#egg=django-suit
```
