### ISSUE TITLE
Sidebar is not properly showing

### ISSUE THREAD

**Issue by shadowwa1k3r** [darklow/django-suit#765]
Version: django-suit-2.0a1
Problem: Sidebar is not showing properly, but I did not get style problems when inspect with browser debugger
![image](https://user-images.githubusercontent.com/22978726/92305015-a4f9ea80-ef9c-11ea-8e3e-63e393356f0d.png)
![image](https://user-images.githubusercontent.com/22978726/92305047-e5596880-ef9c-11ea-81de-71b37e3c8743.png)

**Comment by Mahdi-Ba** [comment]
I have got same problem .
I extend AdminSite Class django and set 
    enable_nav_sidebar = False
create directory  **myadmin** and **apps.py** file  and write  
```
from django.contrib.admin.apps import AdminConfig

class MyAdminConfig(AdminConfig):
    default_site = 'myadmin.admin.MyAdminSite'
```
then like bellow  write in admin.py 
```
from django.contrib import admin
class MyAdminSite(admin.AdminSite):
    enable_nav_sidebar = False
```
then register and replace in settings.py

```
    'suit',
    # 'django.contrib.admin',
    'myadmin.apps.MyAdminConfig',
```

**Comment by Jay-Arr-HummingBird** [comment]
This solution works for me; my development website uses
Python 3.7.6 
suit 2.0a1 
Django 3.1.2 
(I upgraded from Django 2.1.0 today)

**Comment by neerajgupta2407** [comment]
Thanks @Mahdi-Ba for solution
I have created small gist for above issue.
https://gist.github.com/neerajgupta2407/2474f255a4fb5a1f136288c480c91d87
